In [274]:
import os

import numpy as np
import pandas as pd
import glob
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity

# rawdata에서 피험자별 seedword 순서 정보 추출

In [275]:
data_dir = os.getcwd() + '/data/' # data위치 지정
datasets = glob.glob( data_dir + 'raw/' + 'rawdata*.xls' )

In [276]:
seeds_of_subjects = []

# rawdata_study1.xls 피험자 137명
for sheet_index in range(1, 138): 
    seeds_of_each_subject = []
    
    # 시트 차례로 불러오기
    tbl_data = pd.read_excel(datasets[0], sheet_name=f'Sheet{sheet_index}', header=None)
    # row별로 dict 생성
    tbl_data_dict = tbl_data.to_dict('records') # row별로 dict 생성

    for i, value in enumerate(tbl_data_dict):
        if value[4].replace("'", "") == 'seedword':
            seeds_of_each_subject.append(value[10].replace("'", ""))
    seeds_of_subjects.append(seeds_of_each_subject)

In [277]:
# rawdata_study2.xls 피험자 213명
for sheet_index in range(1, 214): 
    seeds_of_each_subject = []
    
    # 시트 차례로 불러오기
    tbl_data = pd.read_excel(datasets[1], sheet_name=f'Sheet{sheet_index}', header=None)
    # row별로 dict 생성
    tbl_data_dict = tbl_data.to_dict('records') # row별로 dict 생성

    for i, value in enumerate(tbl_data_dict):
        if value[4].replace("'", "") == 'seedword':
            seeds_of_each_subject.append(value[10].replace("'", ""))
    seeds_of_subjects.append(seeds_of_each_subject)

In [278]:
print(f'''
seeds_of_subjects는 rawdata엑셀 파일에서, 각 피험자별 seed단어 순서들을 추출해서 저장해둔 배열입니다. \n
{len(seeds_of_subjects)} \n
       ''')
print(f'예시: {seeds_of_subjects[0:3]}')

seeds_of_subjects는 rawdata엑셀 파일에서, 각 피험자별 seed단어 순서들을 추출해서 저장해둔 배열입니다.

350


예시: [['tear', 'family', 'mirror', 'abuse'], ['tear', 'abuse', 'mirror', 'family'], ['family', 'mirror', 'tear', 'abuse']]

# web1, web2 npy데이터 열기

In [279]:
raw_data_dir = os.getcwd() + '/data/raw/' # data위치 지정

# npy 파일 열기
web1_vectors = np.load(raw_data_dir + 'web1-sess1.npy')
web2_vectors = np.load(raw_data_dir + 'web2-sess1.npy')

# vstack: vertical stack을 해주는 함수. 작성 순서대로(왼->오) 순서가 보장된 채로 하나로 합쳐주는 역할
all_data_vectors = np.vstack((web1_vectors, web2_vectors))
# 배열 shape 숫자들을 변수에 저장
n_subject, n_seed, n_response_words, n_dim_of_vector = all_data_vectors.shape

print(f'피험자 숫자: {n_subject}\nseed개수: {n_seed}\nseed당 응답 단어 개수: {n_response_words}\n벡터의 차원: {n_dim_of_vector}')

피험자 숫자: 350
seed개수: 4
seed당 응답 단어 개수: 40
벡터의 차원: 90

In [280]:
total = [] # 전체 벡터데이터 저장할 배열

for i_subject in range(n_subject): ##### 각 피험자의
    response_words_of_each_subject = {
        'subject': i_subject+1, # ex) subject: 1
    }

    for i_seed in range(n_seed): ##### 각 seed단어의
        # rawdata에서 뽑아온 seedword정보에서 해당 피험자 찾아서 seedword가져오기
        seedword = seeds_of_subjects[i_subject][i_seed] 

        for i_word in range(n_response_words): ##### 각 응답단어의 벡터 (90차원)
            # response_words_of_each_subject 딕셔너리에 ex. abuse1_vec 컬럼명을 찾아서 벡터값 저장
            response_words_of_each_subject[f'{seedword}{i_word+1}_vec'] = all_data_vectors[i_subject][i_seed][i_word] # ex) abuse1_vec: 90차원벡터값

    total.append(response_words_of_each_subject)

In [281]:
print(f'number of subject: {len(total)}')
print(f'data of subject1: \n {total[0]}')

number of subject: 350
data of subject1:
 {'subject': 1, 'tear1_vec': array([-2.79974675,  1.00251234, -1.22222555, -0.9890914 ,  1.18628621,
        4.88525486, -1.98106539, -2.03732109, -2.85267663,  2.81611705,
        2.73404026,  7.16165304, -4.44087505,  2.02881861, -2.95463133,
        0.83100581, -0.9974094 , -0.16849989, -1.25637519,  0.47775674,
       -0.6926859 , -2.266855  , -2.72205043,  0.22537686,  0.89014977,
       -1.19019365, -2.10014009,  3.52187634, -1.76154828, -1.11329436,
       -3.43915224, -0.31275928,  3.28120947,  4.59352732, -1.05789196,
       -1.12197518, -2.38847589,  0.91673404, -4.85794258, -0.5881058 ,
       -1.3501513 , -0.41639099, -3.60945988, -3.546947  ,  1.4391768 ,
       -3.10977888,  2.88338351,  5.93057013,  1.29082584,  1.84497523,
       -2.08638811,  1.33774412, -3.15434217,  2.02142429,  3.19965053,
       -0.30009282, -3.69844437,  1.13195777,  0.06201917, -0.02972814,
       -4.44109058,  1.67239642, -3.48865008,  2.62012172,  1.37719274,
       -2.48123288,  2.56780887,  2.15402555,  3.82133126,  0.40491828,
       -4.39993954,  6.01373148,  1.65271437, -2.63257861,  5.39216995,
        2.48435569,  2.45626378, -4.32526779,  0.81052339, -4.93153143,
       -0.07460476, -1.93972325,  0.81993777, -1.95396733,  3.40295815,
       -0.85415161, -3.57652569,  2.80840802, -0.46793041,  1.89198136]), 'tear2_vec': array([-1.50490046,  1.56596935,  1.5032655 , -2.79930902,  1.18123841,
        1.50820231,  0.37617922, -1.08035839, -0.92400962, -2.34527087,
       -0.05401825,  3.68554902,  0.42258805,  1.33374095,  2.4445796 ,
        2.1053803 ,  0.49207455, -2.30744529, -1.6816746 ,  0.50261563,
        1.02714694, -0.80572701,  0.87061614, -0.34131721, -1.1420536 ,
       -1.07702243, -1.76335692,  2.60558987, -1.08188045, -1.2320888 ,
       -1.85633349,  0.60106993,  2.93910623, -0.58170384,  0.35886601,
       -1.69314373, -1.91295981,  0.08406853, -0.5285154 , -1.41879058,
        0.66191435, -1.71761954, -1.6291064 , -2.25015473,  1.63926756,
        0.69659674,  2.23994637,  2.07680893, -1.68838704,  0.28872871,
        1.25207222, -0.12561707, -0.52789021,  0.94852138,  1.15675056,
       -0.83863491, -2.77959752,  1.05432594, -1.36843824,  1.98313296,
       -0.16994976, -1.03529036,  0.92914277,  0.1104391 ,  2.93108773,
       -1.1183157 , -2.22941041,  0.04769974,  1.53121805, -0.53607255,
       -3.9066391 ,  0.11505869,  2.15153551, -0.40840963,  1.31257308,
       -0.56705481,  1.46293473, -2.27559209, -1.25048459, -1.19159925,
       -1.93140769, -2.65228224, -0.05649418,  0.70558387, -0.2245937 ,
       -0.03059592, -0.65242565, -0.83126861, -2.06038857,  0.19327955]), 'tear3_vec': array([ 0.07318285, -0.00467532,  0.07105096,  0.00638106,  0.05592851,
       -0.11566915,  0.0110721 ,  0.0021729 ,  0.07541103,  0.01441464,
       -0.0561346 ,  0.09505679,  0.00431946,  0.01581724,  0.0197305 ,
        0.01878317, -0.06482606, -0.01110308, -0.05616035,  0.00925803,
        0.00661106, -0.02863966,  0.01120063,  0.0381029 ,  0.01698774,
       -0.04926937, -0.05611195, -0.00511408,  0.06776003,  0.08304755,
       -0.0735019 ,  0.01025953,  0.00176578,  0.03178409, -0.09246843,
       -0.01723116, -0.05173638,  0.0081429 , -0.0052965 , -0.00326568,
        0.00536254, -0.08518943, -0.00205189,  0.06605239, -0.01059831,
        0.04676959, -0.03732805, -0.02707677,  0.00812243,  0.05815225,
       -0.00667831, -0.01508751, -0.08457529, -0.01890814, -0.02479711,
       -0.14822806, -0.04664573, -0.0545743 ,  0.01963898, -0.02445482,
       -0.0707169 ,  0.0181862 ,  0.06359296,  0.03787788, -0.00803963,
        0.01840947, -0.06048549, -0.03001831, -0.01156559,  0.00251241,
       -0.02297697, -0.03923814, -0.01503967,  0.00817951, -0.00033953,
       -0.02129583,  0.01938338, -0.00985324,  0.02505885,  0.02342504,
       -0.03787331, -0.04133773,  0.04000217, -0.01831141, -0.02723464,
        0.02388295,  0.01994854, -0.09175655, -0.0121969 , -0.03023998]), 'tear4_vec': array([-0.03984304, -0.03075242,  0.01866061, -0.01274051,  0.07188401,
       -0.04392718,  0.0155602 ,  0.03035401,  0.01644453,  0.05281064,
       -0.02267983,  0.05507451, -0.03506957, -0.01753089,  0.01641233,
       -0.00207586,  0.03924159,  0.00256571,  0.00734584, -0.00510032,
       -0.07746424, -0.03439898,  0.02126258, -0.03886077,  0.04838883,
        0.02093903,  0.00911414, -0.02472122, -0.00714869,  0.05734755,
       -0.03049281,  0.00125397,  0.00233274,  0.02614494, -0.01320404,
        0.07682319, -0.05912944, -0.01769982, -0.02699183, -0.00831009,
       -0.0448595 , -0.0011987 , -0.01795764, -0.01736013,  0.02577272,
        0.01522815, -0.00542365, -0.07857947,  0.0232871 ,  0.03476039,
       -0.0114569 ,  0.00942423, -0.019635  , -0.01130131,  0.00872117,
       -0.03848205,  0.02528981, -0.04525974,  0.00454752,  0.02469671,
       -0.05977046,  0.07167143, -0.01418166,  0.00599625,  0.02463111,
       -0.01484528,  0.01259634,  0.00333467,  0.00237796, -0.07194053,
        0.0081671 , -0.00221951, -0.03298355, -0.00750986, -0.0234019 ,
       -0.02643994,  0.02397787, -0.00091946,  0.00758598, -0.0146565 ,
       -0.02342077, -0.03102927,  0.0375867 , -0.03044626,  0.00034419,
        0.01848036,  0.02811372,  0.01469534,  0.11022722,  0.02410997]), 'tear5_vec': array([-2.13568477e-04,  5.75854921e+00, -1.27032846e-01, -4.89756870e+00,
        4.12374926e+00, -9.24262941e-01, -3.09387779e+00,  2.22872704e-01,
       -2.00390911e+00,  4.23844039e-01,  7.31146857e-02,  8.47833812e-01,
       -2.55000234e+00, -1.09015715e+00, -1.68678129e+00, -3.16263771e+00,
       -1.66448563e-01,  7.05648232e+00,  8.87207031e-01, -1.23343635e+00,
       -2.25289869e+00, -3.98182321e+00, -5.20289168e-02, -1.10437131e+00,
       -6.54365635e+00,  4.32917178e-01, -3.44061032e-02,  1.60009778e+00,
        1.56061327e+00, -4.25978613e+00, -2.84371090e+00,  6.94471931e+00,
        2.74670863e+00, -7.50623345e-01, -6.42221069e+00,  1.19951689e+00,
        4.29516888e+00, -9.93461132e-01,  3.37194180e+00,  1.97772610e+00,
       -2.37545156e+00,  1.24830198e+00, -1.02236140e+00,  4.30538845e+00,
        8.71048927e+00, -1.74134326e+00, -2.93404651e+00,  2.45065308e+00,
        2.60600185e+00, -3.25752044e+00,  5.62137306e-01,  2.35571551e+00,
        2.62667108e+00,  1.13236511e+00,  7.90856719e-01, -5.99439621e-01,
       -4.55469608e+00,  1.74498034e+00, -5.27044773e+00,  3.19915318e+00,
        8.49650502e-01, -2.79234320e-01, -3.97365594e+00,  4.91829014e+00,
        9.61788893e-01,  4.41850805e+00, -2.98793554e+00, -4.99289364e-01,
       -1.97722924e+00,  2.58213460e-01, -3.15468621e+00, -1.42903137e+00,
        2.64821386e+00, -6.90742910e-01,  4.89553690e+00,  6.71896338e-01,
       -1.02948344e+00, -3.10557276e-01,  2.75945842e-01, -2.01972175e+00,
        1.22121048e+00, -6.12582326e-01,  2.93055749e+00, -3.75526577e-01,
       -6.78071976e-01,  3.26631784e+00, -2.94970489e+00, -2.47192264e+00,
        3.21967930e-01, -1.96652210e+00]), 'tear6_vec': array([-0.05162227, -0.08953679, -0.03684232,  0.0946626 ,  0.14861777,
        0.14436735,  0.05478424, -0.06099982,  0.02511645,  0.00272051,
        0.04027925,  0.04644911, -0.08542043, -0.21628593, -0.16496234,
       -0.03179462, -0.11186664, -0.00186468, -0.06349657, -0.15779082,
       -0.28112122, -0.1268238 ,  0.06154617,  0.04901651, -0.03683984,
        0.08623665, -0.00188785, -0.06749361, -0.04458812, -0.03317883,
        0.06909544,  0.03627586, -0.07252733,  0.11433314,  0.01600692,
        0.1209325 ,  0.01680839, -0.11220925,  0.03571303,  0.0653871 ,
        0.13428926,  0.13672456,  0.0021044 , -0.16751921,  0.12007596,
       -0.05069173, -0.08899485,  0.17192392,  0.05248852,  0.16448604,
       -0.13150787, -0.10915675, -0.01982145,  0.04972289,  0.12073585,
        0.11283612, -0.03154884, -0.00725605, -0.02127765, -0.0081407 ,
        0.03465788, -0.07905182, -0.08585564,  0.10538995, -0.02766642,
       -0.05396222,  0.04022618,  0.06591394, -0.11882722, -0.01805855,
        0.0210482 ,  0.09993282, -0.04524092, -0.01451759,  0.03326919,
        0.25809541,  0.15930471, -0.16339667, -0.09816384,  0.05967323,
       -0.08840916, -0.09623779,  0.01440237,  0.10856777,  0.09160133,
        0.08851349, -0.05588783,  0.09952815, -0.03694742,  0.04413728]), 'tear7_vec': array([-1.07667303,  0.10434307,  5.60939884, -0.7434271 ,  2.16124964,
       -1.0769043 , -1.15531921,  1.27768588,  3.52196765,  3.70306158,
        2.81912136,  0.17340763, -2.17113805, -2.04065084,  1.3911705 ,
       -2.85386276, -1.10359478,  3.12274075, -1.55040634, -2.86837506,
       -4.71003628, -3.32855272, -3.36308074, -0.4085989 , -1.61076272,
        1.30048215,  1.64746678,  0.10337436, -2.12839818,  0.05560889,
        0.85426712, -0.63980395, -0.95643044,  1.3471278 , -2.57123733,
       -2.61822224, -1.74073482,  2.99865985, -3.75114059,  0.58715159,
       -2.6435008 , -1.66148913, -2.69330335, -1.32220912,  2.03588772,
       -0.04069059,  2.07770419,  1.60451043, -3.04402375, -1.74845064,
       -2.94659376,  4.83886051,  5.68680048,  2.10503244, -0.20901752,
       -1.22375226, -4.3721509 , -1.19645524, -3.62987542,  0.73164636,
        0.27417186,  1.60011399, -4.16579771,  1.09663165,  1.16741645,
        0.01877476, -7.12556458, -3.74613214,  2.21549559, -0.83469152,
        0.25737223,  1.40451217, -1.02783871,  5.60487795,  3.0855732 ,
       -2.14230323, -3.43005633,  0.13761537,  4.91714287,  0.00800184,
        0.48905495,  2.53456092, -2.33364296, -3.93686795, -2.12483025,
       -0.85846287, -1.62650263,  3.2483995 , -2.13931322,  0.95259678]), 'tear8_vec': array([ 2.42492914,  3.60717368, -3.38767529,  2.28019333,  3.02086782,
        6.54094696, -0.58998179, -0.73218292,  0.20839025,  0.25665724,
        1.59614778,  5.53750896, -1.32350826,  1.56698811, -4.99109459,
       -3.72566414, -1.25418556, -1.31713581, -0.33894166, -2.81503558,
       -1.72241926,  0.55089992,  1.06886566,  4.55569792,  0.91792613,
        2.82971144, -2.58594394, -1.79290903, -1.62107825,  1.09235871,
       -3.45732808,  0.15051411, -0.28410959,  2.48774958,  1.40167558,
        0.3159329 , -1.77618802, -5.79245424, -5.55859661,  2.89441895,
        0.1181789 , -0.05481979, -1.15443766, -2.4734199 , -0.86082536,
       -2.88970184,  2.49274135,  3.68889189,  3.0044868 ,  2.97722793,
       -3.3980906 ,  2.79115295, -1.97796714,  1.6470629 ,  3.97247505,
        2.26340437, -4.94594479,  0.23461284, -1.10700476, -0.39298055,
       -6.11344147,  1.14000583, -2.3459394 ,  5.79640102,  4.90102625,
       -4.73117876,  0.44844916,  1.64841998,  4.41294909,  0.03835852,
       -3.79563236,  8.09105301,  2.01120019, -1.96609688,  2.24599481,
        1.20413733,  2.80782151, -4.37005711, -0.07130065, -0.33673936,
        0.65258706, -3.68696499,  2.41099238, -2.57261205,  2.557163  ,
        1.75175381, -3.44362283,  2.02156067,  1.443712  ,  2.31572318]), 'tear9_vec': array([ -5.87629867,   0.33746338,  -2.54965743,  -5.13333607,
         0.37877452,   1.53065918,   3.48743117,  -0.63663793,
        -7.03646824,   1.77893633,   8.10968184,  11.74431181,
        -8.85825586,   4.73523414,   0.55540228,  -6.06629986,
         1.13515481,  -2.62757373,  -1.19299495,  -3.85702592,
       -10.6611439 ,  -7.99577403,   2.45974362,   3.23503017,
         3.87677836,   3.64985383,  -5.41625659,   6.15782988,
        -1.0003528 ,   2.79798981,  -5.07775652,   3.3873235 ,
         2.65840209,   3.63396573,  -0.64564833,   5.26640999,
        -5.17678654,  -1.07608923, -12.17124224,   1.43464619,
         1.25755499,   0.29834709,  -3.57127964,  -8.31150079,
        -3.77975571,  -1.49703044,   7.08992767,   6.76387119,
         2.38719493,  -5.28184831,  -4.49416506,   3.14740127,
        -0.50333759,   3.04779381,  10.99515915,   1.73614079,
       -10.16370273,   2.0421437 ,  -3.06299207,  -1.89152074,
        -4.38503377,   1.97675832,  -8.89543855,   8.16990006,
        -0.42876291,  -3.25640187,  -1.94981474,   5.23442388,
         9.70041943,  -7.33006001,  -4.32619977,   6.77610493,
        -1.07047081,  -3.95441681,   6.77391577,   0.55125496,
         9.19695616,  -0.9116273 ,  -2.33402491,  -7.69186616,
        -0.99164003,  -8.26106286,   2.22836521,  -1.87023264,
         3.76713842,   1.98963946,  -3.46984327,   5.02211618,
         1.25466901,   4.31172231]), 'tear10_vec': array([-0.83076978, -1.7025882 ,  0.22040631,  0.45788977,  0.8526091 ,
        1.11947393, -1.78753352,  0.80138522, -3.12268162, -1.72148454,
        0.5364939 ,  2.9933579 , -2.14654779,  0.88930106,  0.09943488,
        1.01384866,  0.4740158 , -0.54342633, -0.62172222, -0.20963018,
       -1.25093794, -2.58139348, -0.58900952,  0.98009068,  0.46009514,
        0.00486698,  1.4665333 ,  0.91054714, -0.06703459,  0.52570766,
       -1.36981893, -0.22728942,  1.23819697,  0.64865321, -0.50445467,
        2.51771545, -1.88230026, -2.27446508, -2.01657724, -2.15097857,
       -0.97273773,  0.02856829, -1.04273391, -1.72671497,  0.03911046,
        0.12715824,  2.22338748,  2.08746433,  0.71747518,  0.47165191,
       -2.71425176,  0.17835222, -1.81623113,  0.80362982,  1.77682793,
        0.90338671, -0.56275505,  0.21790588, -1.5871464 , -1.7191633 ,
        0.55938059, -0.89050078, -0.87383407,  1.76427805,  0.67418176,
        0.4680863 ,  1.89852631,  0.57998413,  0.64127064,  0.37039474,
       -0.25345108,  1.56538844,  0.91065544, -1.00948989,  1.18714321,
        0.43239617,  2.31420612, -0.53060222, -0.34448627, -0.12012287,
       -2.09434319, -0.79417008, -0.30368862,  0.64847583,  0.22982585,
       -0.61000669,  0.01466208,  0.59549016, -1.21243703,  0.54653305]), 'tear11_vec': array([-4.18612361e-03,  3.16164567e+00, -4.09902072e+00, -2.40078846e+00,
        6.04235470e+00,  7.20138264e+00, -6.91462755e+00,  1.04793310e+00,
       -4.19737452e+00,  1.47770850e+00,  4.46579528e+00,  1.43038106e+01,
       -4.08956933e+00, -1.78820936e+00, -8.65120912e+00, -1.49920001e+00,
       -3.85542893e+00, -3.27699792e+00, -1.63972899e+00, -4.45926929e+00,
        1.41330940e+00, -9.81186688e-01, -2.58429193e+00,  4.41681743e-02,
       -3.86154801e-01, -2.46852733e+00, -5.51681221e+00, -2.28736368e+00,
       -2.18395999e+00,  3.57876563e+00, -5.68614769e+00, -1.74253106e+00,
        6.39507985e+00, -1.12190801e+00,  2.81423591e+00,  2.02294114e+00,
       -6.54747844e+00, -1.21005753e+00, -9.79046011e+00, -1.83138102e+00,
       -3.37315798e+00, -9.88547921e-01,  9.92883563e-01, -1.02083032e+01,
       -2.61454785e+00, -9.20359015e-01, -2.90167761e+00,  4.29841621e+00,
        4.67068315e+00,  7.98804648e-01, -4.70816135e+00, -1.11775860e+00,
       -5.54391015e+00, -5.67335606e-01,  4.58456731e+00,  7.23027754e+00,
       -2.23279381e+00, -1.41966808e+00,  5.14984995e-01,  4.05411410e+00,
       -9.95985103e+00, -6.46378350e+00, -3.00939059e+00,  2.83705407e+00,
        3.38622010e+00, -7.37883663e+00,  5.22551374e+00,  6.95082378e+00,
        3.63431776e+00, -3.41459191e+00, -7.40849996e+00,  4.82297451e+00,
       -2.02185249e+00, -6.16787076e-01,  3.37133944e+00,  6.29006803e-01,
        9.22872376e+00, -1.09543643e+01, -3.73468280e-01, -5.50670099e+00,
       -2.40424646e+00, -6.21896815e+00, -4.59320307e+00,  2.91200539e+00,
        8.14093494e+00, -7.42331529e+00,  3.88006532e+00, -8.55389476e-01,
       -9.12166238e-02,  4.79425138e+00]), 'tear12_vec': array([-0.17210495, -1.90756655, -1.78180325, -1.99986994,  2.20799851,
        5.37100077, -1.29773796, -0.97105455, -6.79124546, -2.99874067,
        2.9150157 ,  5.17077255, -3.59994268,  0.33218509, -7.370327  ,
        0.42114756, -2.14239216, -0.87764591,  0.50549752, -0.13071612,
       -1.84782767, -6.12950134,  1.17324257,  0.94318199, -2.09923768,
        0.19186488,  0.02150813,  0.14133504, -3.50582814,  0.19452825,
       -3.01261139, -0.22328238,  2.55654669,  2.19399238, -2.2631247 ,
        0.19692393, -2.08187246, -2.01816368, -6.82586718, -1.48605001,
        0.84159547, -4.09014463, -4.07005978, -0.40192679,  1.57975841,
        2.17560172,  1.62613571,  4.96738482,  3.63120365,  4.1452117 ,
       -2.37472796, -0.24283329, -3.53085899, -0.05521661,  2.90566254,
        5.65498829, -1.44334579, -1.18982828, -1.73868954, -2.74891949,
       -6.13026237,  2.39047861, -1.02186656,  4.71681786, -0.18620093,
       -3.62588763,  0.50264764,  3.40351248,  2.53924108, -0.61829382,
       -1.79661775,  4.85238981, -3.31673646, -4.00677919,  0.83516246,
        4.16758442,  5.92728901, -1.59146547,  1.2454958 , -6.068048  ,
        0.23991962, -3.97517586, -1.69857299, -2.96721649,  0.25968289,
        0.7090134 , -5.29787111,  1.56938672, -3.1330514 ,  4.3538332 ]), 'tear13_vec': array([-2.79974675,  1.00251234, -1.22222555, -0.9890914 ,  1.18628621,
        4.88525486, -1.98106539, -2.03732109, -2.85267663,  2.81611705,
        2.73404026,  7.16165304, -4.44087505,  2.02881861, -2.95463133,
        0.83100581, -0.9974094 , -0.16849989, -1.25637519,  0.47775674,
       -0.6926859 , -2.266855  , -2.72205043,  0.22537686,  0.89014977,
       -1.19019365, -2.10014009,  3.52187634, -1.76154828, -1.11329436,
       -3.43915224, -0.31275928,  3.28120947,  4.59352732, -1.05789196,
       -1.12197518, -2.38847589,  0.91673404, -4.85794258, -0.5881058 ,
       -1.3501513 , -0.41639099, -3.60945988, -3.546947  ,  1.4391768 ,
       -3.10977888,  2.88338351,  5.93057013,  1.29082584,  1.84497523,
       -2.08638811,  1.33774412, -3.15434217,  2.02142429,  3.19965053,
       -0.30009282, -3.69844437,  1.13195777,  0.06201917, -0.02972814,
       -4.44109058,  1.67239642, -3.48865008,  2.62012172,  1.37719274,
       -2.48123288,  2.56780887,  2.15402555,  3.82133126,  0.40491828,
       -4.39993954,  6.01373148,  1.65271437, -2.63257861,  5.39216995,
        2.48435569,  2.45626378, -4.32526779,  0.81052339, -4.93153143,
       -0.07460476, -1.93972325,  0.81993777, -1.95396733,  3.40295815,
       -0.85415161, -3.57652569,  2.80840802, -0.46793041,  1.89198136]), 'tear14_vec': array([-2.79974675,  1.00251234, -1.22222555, -0.9890914 ,  1.18628621,
        4.88525486, -1.98106539, -2.03732109, -2.85267663,  2.81611705,
        2.73404026,  7.16165304, -4.44087505,  2.02881861, -2.95463133,
        0.83100581, -0.9974094 , -0.16849989, -1.25637519,  0.47775674,
       -0.6926859 , -2.266855  , -2.72205043,  0.22537686,  0.89014977,
       -1.19019365, -2.10014009,  3.52187634, -1.76154828, -1.11329436,
       -3.43915224, -0.31275928,  3.28120947,  4.59352732, -1.05789196,
       -1.12197518, -2.38847589,  0.91673404, -4.85794258, -0.5881058 ,
       -1.3501513 , -0.41639099, -3.60945988, -3.546947  ,  1.4391768 ,
       -3.10977888,  2.88338351,  5.93057013,  1.29082584,  1.84497523,
       -2.08638811,  1.33774412, -3.15434217,  2.02142429,  3.19965053,
       -0.30009282, -3.69844437,  1.13195777,  0.06201917, -0.02972814,
       -4.44109058,  1.67239642, -3.48865008,  2.62012172,  1.37719274,
       -2.48123288,  2.56780887,  2.15402555,  3.82133126,  0.40491828,
       -4.39993954,  6.01373148,  1.65271437, -2.63257861,  5.39216995,
        2.48435569,  2.45626378, -4.32526779,  0.81052339, -4.93153143,
       -0.07460476, -1.93972325,  0.81993777, -1.95396733,  3.40295815,
       -0.85415161, -3.57652569,  2.80840802, -0.46793041,  1.89198136]), 'tear15_vec': array([ 0.23031011, -0.17817797,  0.01580164, -0.20116411,  0.23956095,
        0.39667028, -0.34207612, -0.52356225,  0.35155013, -0.04723808,
        0.32858992,  0.46218383,  0.03488327,  0.05823355,  0.12302726,
       -0.03388433,  0.36391604, -0.27665761, -0.30501977,  0.08185419,
       -0.32023472, -0.14340565,  0.01569839,  0.44753343, -0.37309295,
        0.28991458,  0.6044302 ,  0.2124967 , -0.51322699, -0.43925655,
       -0.32250226, -0.18237671,  0.28869864,  0.14034873,  0.36184201,
        0.24476345, -0.21971963, -0.0549712 , -0.19123393, -0.08745412,
        0.09849671,  0.0630374 , -0.2331796 , -0.30742335,  0.0164492 ,

In [282]:
all_data_df = pd.DataFrame(total)
all_data_df

,subject,tear1_vec,tear2_vec,tear3_vec,tear4_vec,tear5_vec,tear6_vec,tear7_vec,tear8_vec,tear9_vec,...,abuse31_vec,abuse32_vec,abuse33_vec,abuse34_vec,abuse35_vec,abuse36_vec,abuse37_vec,abuse38_vec,abuse39_vec,abuse40_vec
0,1,"[-2.7997467517852783, 1.0025123357772827, -1.2...","[-1.5049004554748535, 1.5659693479537964, 1.50...","[0.0731828510761261, -0.004675315693020821, 0....","[-0.03984304144978523, -0.03075242042541504, 0...","[-0.00021356847719289362, 5.758549213409424, -...","[-0.05162226781249046, -0.08953678607940674, -...","[-1.0766730308532715, 0.10434307157993317, 5.6...","[2.424929141998291, 3.6071736812591553, -3.387...","[-5.876298666000366, 0.33746337890625, -2.5496...",...,"[0.3068299889564514, -5.440547704696655, -0.15...","[-3.669671967625618, -5.602187544107437, 0.863...","[0.4952196478843689, 2.1568381786346436, 1.788...","[2.353285074234009, 3.7313449382781982, -0.480...","[1.4057475328445435, 2.7502248287200928, 3.187...","[3.951447606086731, 1.5583451390266418, -0.109...","[2.310206413269043, 1.7991424798965454, 2.6263...","[5.4977288246154785, -1.2148534059524536, 4.73...","[-5.164267539978027, -0.7331278324127197, 1.05...","[-0.35834380984306335, 1.018376350402832, -0.7..."
1,2,"[-2.7997467517852783, 1.0025123357772827, -1.2...","[0.45708733797073364, -0.6215798258781433, -0....","[-5.959320068359375, 6.186459600925446, -2.712...","[-2.988236904144287, 0.7769572138786316, 0.323...","[0.5567496418952942, -2.2172653675079346, 2.29...","[1.8707859516143799, -1.1655787229537964, 1.85...","[-1.9872565269470215, -9.86076545715332, 2.282...","[-1.0783004760742188, 1.3618557453155518, -2.3...","[-0.757293164730072, -0.211566761136055, -0.84...",...,"[-2.8006346225738525, -3.958317756652832, -1.5...","[-2.8006346225738525, -3.958317756652832, -1.5...","[-1.9371036291122437, -3.3271970748901367, -3....","[1.769850254058838, 3.052565097808838, -3.1117...","[0.18298132717609406, 1.612946629524231, -3.05...","[0.1730307936668396, 0.038090191781520844, 0.1...","[2.647094964981079, 0.6997803449630737, -1.559...","[-0.17232778668403625, -5.012906551361084, -6....","[-2.4440691471099854, -0.8925318717956543, -0....","[1.687965750694275, -0.9570441842079163, 1.968..."
2,3,"[-0.14277277886867523, 0.17866025865077972, -1...","[-0.05008912459015846, 4.079308986663818, -5.3...","[1.6711207628250122, -4.349452972412109, -2.34...","[-1.169617772102356, 0.7114548683166504, -2.06...","[1.765024185180664, -1.3058565855026245, -5.42...","[-0.1085025742650032, 0.5090253949165344, -2.0...","[2.6600513458251953, 1.1037150621414185, -1.56...","[2.0577778816223145, 2.3813185691833496, 3.318...","[-5.1105570793151855, 0.6133217215538025, -2.9...",...,"[-1.3444898128509521, -1.9484931230545044, -3....","[-0.5626689195632935, 1.0186009407043457, 1.79...","[-0.004942434839904308, -0.00423665763810277, ...","[7.317351341247559, 0.19146670401096344, -0.83...","[-0.7530180811882019, -0.4503012001514435, 0.6...","[3.7946832180023193, 1.2103089094161987, -0.39...","[-6.381642818450928, -0.25714749097824097, 2.7...","[-0.8012444376945496, -1.6405866146087646, 1.0...","[-0.679341197013855, -0.5665156245231628, -0.2...","[-1.0201469659805298, -2.0769898891448975, 0.1..."
3,4,"[-4.05358362197876, -2.1990063190460205, -2.74...","[0.006588673684746027, 0.11960766464471817, -0...","[-3.8310554027557373, 0.4362701177597046, -1.6...","[-4.372428119182587, 7.190983533859253, 6.6034...","[1.6293264627456665, 3.593465566635132, -4.204...","[-1.5804722309112549, -1.4650334119796753, -1....","[-0.4196225702762604, -3.142327070236206, -5.8...","[0.22102010250091553, -3.767268657684326, -6.0...","[0.1270749568939209, -1.7401845455169678, -4.4...",...,"[4.43143367767334, 2.9310171604156494, -0.9024...","[-4.698283672332764, 0.11811280995607376, 6.05...","[-0.8674511909484863, -0.18062961101531982, 0....","[-4.729660511016846, -1.2575398683547974, 5.03...","[-1.4293122291564941, 0.7171301245689392, 1.09...","[-5.283805847167969, -4.199435710906982, 1.504...","[-1.6902824640274048, -6.228943824768066, -4.4...","[-0.1355506032705307, -0.05910854414105415, -0...","[-0.9625242352485657, -1.2798689603805542, -0....","[0.8531345725059509, -1.6442772150039673, -1.5..."
4,5,"[-0.6399512887001038, -0.17453934252262115, -0...","[-2.7997467517852783, 1.0025123357772827, -1.2...","[-0.8217383027076721, -4.030311584472656, -3.3...","[-5.688853740692139, 3.0388669967651367, -2.61...","[-4.573505878448486, 1.9573383331298828, -2.00...","[-4.573505878448486, 1.9573383331298828, -2.00...","[-4.573505878448486, 1.9573383331298828, -2.00...","[-4.573505878448486, 1.9573383331298828, -2.00...","[-4.573505878448486, 1.9573383331298828, -2.00...",...,"[-0.7846636176109314, 0.9534463882446289, 0.47...","[-3.9166860580444336, 2.9676191806793213, -3.6...","[7.016181468963623, -1.6751666069030762, -0.27...","[-0.5882290601730347, 2.755230665206909, -2.36...","[-0.9763079881668091, 4.537396430969238, -1.07...","[-0.30190417170524597, 2.4203603267669678, 0.0...","[1.6646913886070251, -2.9990983605384827, -1.6...","[-4.912431716918945, 1.6661125421524048, -1.51...","[3.3739230632781982, -1.044118046760559, 1.861...","[1.6852389574050903, -2.600393056869507, -0.74..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,"[-2.7997467517852783, 1.0025123357772827, -1.2...","[-2.1541707515716553, 3.547475576400757, -1.36...","[0.6160911917686462, -2.879063844680786, 1.666...","[-0.47477829456329346, -1.3410383462905884, 2....","[0.3930572271347046, -1.049180269241333, 0.095...","[-5.456510066986084, -4.251359462738037, -2.61...","[-0.691895067691803, -1.0489025115966797, 0.29...","[1.9434666633605957, 1.7679810523986816, 0.998...","[-9.87470531463623, 3.8849105834960938, -3.042...",...,"[-1.871178388595581, -0.7805203199386597, -2.7...","[-0.5629376173019409, 1.1249562501907349, -2.1...","[-0.6784165501594543, -2.8503429889678955, -1....","[0.8338707089424133, -1.693352222442627, -1.81...","[-0.5597984194755554, 0.11009116470813751, -1....","[-5.748339891433716, -1.2757347226142883, -1.6...","[-0.08807756006717682, -0.00011733802239177749...","[-0.9390287399291992, 4.624797344207764, -0.87...","[3.7946832180023193, 1.2103089094161987, -0.39...","[0.4951622784137726, 3.3341565132141113, 0.739..."
346,347,"[-1.9440072774887085, -5.705893516540527, 1.21...","[-3.703439950942993, -8.684242248535156, 2.691...","[0.6485453248023987, -3.697143793106079, 2.207...","[0.4952196478843689, 2.1568381786346436, 1.788...","[-3.4590883255004883, 1.2283952236175537, -0.0...","[-0.8476470112800598, -1.4354602098464966, -2....","[4.255696773529053, -2.5270957946777344, -2.76...","[-0.9123436212539673, -0.13178938627243042, -2...","[-0.8899287581443787, -2.259491443634033, -0.6...",...,"[0.3738552927970886, 0.33312997221946716, -2.3...","[-0.5337938070297241, 0.22830697894096375, 0.9...","[-2.000359058380127, 7.959123611450195, -0.746...","[-0.9447075128555298, 2.7596380710601807, -0.1...","[1.0283386707305908, 2.243319034576416, -2.875...","[4.255696773529053, -2.5270957946777344, -2.76...","[-1.9130220413208008, -0.12310945242643356, 0....","[-0.23031678795814514, 4.56700325012207, -1.00...","[-0.5801510810852051, -0.8177824020385742, -1....","[5.437158584594727, 0.1796962022781372, -4.454..."
347,348,"[-2.6546874046325684, -2.3235628604888916, 0.4...","[-2.7878217697143555, -2.7050297260284424, -0....","[0.12405288964509964, -5.623889923095703, 0.77...","[-0.5311386585235596, 0.6390263438224792, 0.22...","[-2.150083303451538, -2.244920015335083, -3.94...","[-2.1562821865081787, 1.1971659660339355, -0.3...","[-0.2213830202817917, -1.3564635515213013, -2....","[2.6842994689941406, -2.5851964950561523, -4.1...","[3.5723776817321777, 0.47051769495010376, 0.96...",...,"[0.21802647411823273, 1.1676141023635864, -2.9...","[1.6801549196243286, 1.8149787187576294, -2.81...","[-0.3180481791496277, -0.5335749983787537, -1....","[0.03692324087023735, -0.10297508537769318, -0...","[0.9680685997009277, 0.35843145847320557, 0.98...","[-1.6364668607711792, 5.107818126678467, -0.35...","[-0.03615257516503334, -0.4973013401031494, -0...","[0.19018666446208954, 0.042461324483156204, 0....","[0.6076529622077942, 5.170889377593994, -0.864...","[1.5973845720291138, -1.5754302740097046, -4.1..."
348,349,"[-3.8115341663360596, -1.1908419132232666, -0....","[-2.75750994682312, -4.143979072570801, 0.7118...","[-2.7293457984924316, -3.3161187171936035, -3....","[-4.869290828704834, -2.702784538269043, -2.63...","[6.02250862121582, 0.9909096360206604, -2.0359...","[-5.187849044799805, 1.2624865770339966, 0.576...","[-3.1983258724212646, -2.322077989578247, -0.4...","[-0.6202675700187683, -3.6764135360717773, -1....","[0.5624351501464844, 0.9910527467727661, -2.91...",...,"[-8.72448444366455, 1.540122151374817, 3.36635...","[-3.464094400405884, -0.03468449413776398, 1.9...","[0.630594789981842, -0.6323292851448059, -2.57...","[-1.494275450706482, -1.8948841094970703, -0.1...","[-3.8115341663360596, -1.1908419132232666, -0....","[-6.199105262756348, -0.7752066850662231, 0.42...","[-3.0748302936553955, -2.856689214706421, -1.2...","[-4.470478534698486, 0.04554159566760063, -2.2...","[-5.35028600692749, 7.076805591583252, -4.2990...","[-2.1562821865081787, 1.1971659660339355, -0.3..."
349,350,"[0.6435839533805847, 3.9796035289764404, 0.774...","[-1.7098890542984009, 2.167245626449585, -1.58...","[0.5953068137168884, 0.9298314452171326, -0.01...","[4.457800388336182, 4.757269859313965, -3.1887...","[3.399596929550171, 2.775204658508301, 0.64550...","[4.126007080078125, 1.722745418548584, -0.3676...","[-8.607069492340088, -5.57229483127594, -2.408...","[-1.7284184694290161, 2.9920384883880615, 1.02...","[-3.099513530731201, -1.1488395929336548, 0.31...",...,"[-4.3276896476745605, -4.190338611602783, 0.17...","[-0.5851927399635315, -0.1671276092529297, 0.1...","[-0.46458303928375244, -0.9643694162368774, -0...","[-1.0787302255630493, -0.9470697641372681, 2.0...","[0.23342712223529816, -2.5146117210388184, 0.9...","[1.2169084548950195, 1.0353983640670776, 1.561...","[0.014865493401885033, -0.11250067502260208, 0...","[0.869457483291626, -2.098245143890381, -0.376...","[0.5520885586738586, -1.5346317291259766, 1.59...","[4.255696773529053, -2.5270957946777344, -2.76..."

# similarity - coherence

유사도 방법론: https://wikidocs.net/24654

코드 구성은 기본적으로 2_get_similarity_and_coherence.ipynb와 동일합니다.

In [283]:
# loading the word2vec model
word2vec_model = KeyedVectors.load_word2vec_format('pretrained/GoogleNews-vectors-negative300.bin', binary=True)
# print(word2vec_model['king']) # 모델이 잘 로드되었는지 확인

In [284]:
seed_words = ['abuse', 'tear', 'mirror', 'family'] # 학대, 눈물, 거울, 가족
target_words = ['money', 'friend', 'relationships', 'family']

In [285]:
# coherence 컬럼 미리 생성(빈 값)
for seed_word in seed_words:
    for target_word in target_words:
        column_name = f'coherence_{seed_word}_{target_word}'
        all_data_df = all_data_df.assign(**{column_name: None})

all_data_df.iloc[0:3]

,subject,tear1_vec,tear2_vec,tear3_vec,tear4_vec,tear5_vec,tear6_vec,tear7_vec,tear8_vec,tear9_vec,...,coherence_tear_relationships,coherence_tear_family,coherence_mirror_money,coherence_mirror_friend,coherence_mirror_relationships,coherence_mirror_family,coherence_family_money,coherence_family_friend,coherence_family_relationships,coherence_family_family
0,1,"[-2.7997467517852783, 1.0025123357772827, -1.2...","[-1.5049004554748535, 1.5659693479537964, 1.50...","[0.0731828510761261, -0.004675315693020821, 0....","[-0.03984304144978523, -0.03075242042541504, 0...","[-0.00021356847719289362, 5.758549213409424, -...","[-0.05162226781249046, -0.08953678607940674, -...","[-1.0766730308532715, 0.10434307157993317, 5.6...","[2.424929141998291, 3.6071736812591553, -3.387...","[-5.876298666000366, 0.33746337890625, -2.5496...",...,None,None,None,None,None,None,None,None,None,None
1,2,"[-2.7997467517852783, 1.0025123357772827, -1.2...","[0.45708733797073364, -0.6215798258781433, -0....","[-5.959320068359375, 6.186459600925446, -2.712...","[-2.988236904144287, 0.7769572138786316, 0.323...","[0.5567496418952942, -2.2172653675079346, 2.29...","[1.8707859516143799, -1.1655787229537964, 1.85...","[-1.9872565269470215, -9.86076545715332, 2.282...","[-1.0783004760742188, 1.3618557453155518, -2.3...","[-0.757293164730072, -0.211566761136055, -0.84...",...,None,None,None,None,None,None,None,None,None,None
2,3,"[-0.14277277886867523, 0.17866025865077972, -1...","[-0.05008912459015846, 4.079308986663818, -5.3...","[1.6711207628250122, -4.349452972412109, -2.34...","[-1.169617772102356, 0.7114548683166504, -2.06...","[1.765024185180664, -1.3058565855026245, -5.42...","[-0.1085025742650032, 0.5090253949165344, -2.0...","[2.6600513458251953, 1.1037150621414185, -1.56...","[2.0577778816223145, 2.3813185691833496, 3.318...","[-5.1105570793151855, 0.6133217215538025, -2.9...",...,None,None,None,None,None,None,None,None,None,None

In [286]:
# 원래의 300차원 워드 벡터 생성
money_vec = word2vec_model['money'][:90]
friend_vec = word2vec_model['friend'][:90]
relationships_vec = word2vec_model['relationships'][:90]
family_vec = word2vec_model['family'][:90]

for seed_word in seed_words:
    coherences_money_per_sub = []
    coherences_friend_per_sub = []
    coherences_relationships_per_sub = []
    coherences_family_per_sub = []
    
    word_columns = [seed_word + str(i) for i in range(1, n_response_words + 1)]

    for i_subject in range( n_subject): # 1 ~ 350번 피험자
        each_seed_similarities_money = []  
        each_seed_similarities_friend = []  
        each_seed_similarities_relationships = []
        each_seed_similarities_family = []

        for i, column in enumerate(word_columns): # 각각 seed1~40
            try:
                similarity_between_money = cosine_similarity(all_data_df.iloc[i_subject][f'{column}_vec'].reshape(1, -1), money_vec.reshape(1, -1))[0][0]
                similarity_between_friend = cosine_similarity(all_data_df.iloc[i_subject][f'{column}_vec'].reshape(1, -1), friend_vec.reshape(1, -1))[0][0]
                similarity_between_relationships = cosine_similarity(all_data_df.iloc[i_subject][f'{column}_vec'].reshape(1, -1), relationships_vec.reshape(1, -1))[0][0]
                similarity_between_family = cosine_similarity(all_data_df.iloc[i_subject][f'{column}_vec'].reshape(1, -1), family_vec.reshape(1, -1))[0][0]

                each_seed_similarities_money.append(similarity_between_money) # 40개
                each_seed_similarities_friend.append(similarity_between_friend) # 40개
                each_seed_similarities_relationships.append(similarity_between_relationships) # 40개
                each_seed_similarities_family.append(similarity_between_family) # 40개
            except Exception:
                continue  
        # 해당 피험자가 하나의 seed에 답한 40개의 응답단어의 유사도의 coherence값
        money_coherence_of_seed_per_sub = np.mean(each_seed_similarities_money) 
        friend_coherence_of_seed_per_sub = np.mean(each_seed_similarities_friend)
        relationships_coherence_of_seed_per_sub = np.mean(each_seed_similarities_relationships) 
        family_coherence_of_seed_per_sub = np.mean(each_seed_similarities_family)

        # 해당 피험자에 대한, 그 seed단어 각각(4개)에 대한 coherence값
        # 피험자마자 16개값( abuse,tear,mirror,family - money,friend,relationships,family 조합)
        coherences_money_per_sub.append(money_coherence_of_seed_per_sub)
        coherences_friend_per_sub.append(friend_coherence_of_seed_per_sub)
        coherences_relationships_per_sub.append(relationships_coherence_of_seed_per_sub)
        coherences_family_per_sub.append(family_coherence_of_seed_per_sub)

        # Append the coherence values to the data frame for the current subject
        all_data_df.at[i_subject, f'coherence_{seed_word}_money'] = money_coherence_of_seed_per_sub
        all_data_df.at[i_subject, f'coherence_{seed_word}_friend'] = friend_coherence_of_seed_per_sub
        all_data_df.at[i_subject, f'coherence_{seed_word}_relationships'] = relationships_coherence_of_seed_per_sub
        all_data_df.at[i_subject, f'coherence_{seed_word}_family'] = family_coherence_of_seed_per_sub

In [305]:
drop_columns = all_data_df.columns[1:161] # vector 컬럼들 드롭
all_data_df = all_data_df.drop(drop_columns, axis='columns')
all_data_df[0:3]

,subject,coherence_abuse_money,coherence_abuse_friend,coherence_abuse_relationships,coherence_abuse_family,coherence_tear_money,coherence_tear_friend,coherence_tear_relationships,coherence_tear_family,coherence_mirror_money,coherence_mirror_friend,coherence_mirror_relationships,coherence_mirror_family,coherence_family_money,coherence_family_friend,coherence_family_relationships,coherence_family_family
0,1,-0.0339,-0.070248,0.033578,0.038118,-0.015877,-0.09457,0.016956,0.040386,-0.03468,-0.056288,0.010468,0.011554,-0.014061,-0.042279,0.048968,0.034762
1,2,-0.041405,-0.053929,-0.005651,-0.014738,-0.033688,-0.09907,0.004897,-0.048921,0.006353,-0.053232,-0.014116,-0.000326,-0.026695,-0.065986,0.029354,-0.040201
2,3,-0.062901,-0.062581,0.053195,-0.004476,-0.004859,-0.04779,0.009106,0.049194,-0.053489,-0.067074,0.038215,0.040049,-0.042503,-0.085476,-0.011849,-0.007311

In [307]:
all_data_df.to_csv(data_dir + 'processed/similarity_coherence_data_90.csv', index=None)