# response words check

word2vec 사전에 없는 단어들을 걸러내는 코드입니다. \
이후 수동으로 전처리 작업에 추가할 예정입니다. 결과는 need_to_be_fixed.csv 파일에서 확인할 수 있습니다.

In [180]:
import os
import re

import pandas as pd
from gensim.models import KeyedVectors

In [181]:
pilot2_dir = os.getcwd()

# loading the word2vec model
word2vec_model = KeyedVectors.load_word2vec_format(pilot2_dir + '/../pretrained/GoogleNews-vectors-negative300.bin', binary=True)
# print(word2vec_model['Eiffel']) # 모델이 잘 로드되었는지 확인

In [183]:
word2vec_model.most_similar(['Piazza', 'Brazil'])

[('Abreu', 0.5686987042427063),
 ('Italy', 0.5649343729019165),
 ('Brazilian', 0.5555433034896851),
 ('Adriano', 0.5483388304710388),
 ('Argentina', 0.542917013168335),
 ('Sao_Paulo', 0.5422480702400208),
 ('Leandro_Guilheiro', 0.5345199108123779),
 ('Uruguay', 0.5292974710464478),
 ('Santo_Andre', 0.5271482467651367),
 ('San_Paolo', 0.5266311168670654)]

In [184]:
processed_data_dir = os.getcwd() + '/data/processed/' # data위치 지정

pilot_data = pd.read_csv(processed_data_dir + 'merged_data.csv')
pilot_data[0:3]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,friend21,friend22,friend23,friend24,friend25,friend26,friend27,friend28,friend29,friend30
0,5d53bffa147a7d00015aae5a,1,Door,Gate,Outside,Grass,Itchy,Rash,Chicken pox,Shingles,...,Burned down,Scary,Movies,Knocked up,Tinsletown,Christmas tree,Holiday,Decorate,Fun,Party
1,5f00ec86304f7322eb8dfa41,2,Unlock,Door,Enter,Dreams,Time and space,Possibilites,Infinite,Time,...,Transparent,Glass,Shattered,Repair,Meaningful,Bond,Glue,All together,Matters,Wonders
2,5de27ced22383629b807cc70,3,Hole,Ground,Hog,Pig,Pork,Sald,Dressing,Clothes,...,Sunshine,Wamrth,Blanket,Heavy,Body,Muscle,Protein,Shake,Dance,Jump

In [185]:
# 기존 데이터프레임을 복사하여 새로운 데이터프레임 생성
processed_data = pilot_data.copy()

# seed_words와 n_respond_words를 정의
seed_words = ['key', 'money', 'friend']
n_respond_words = 30

# 피험자 수와 차원을 설정 (실제 데이터에 따라 적절한 값으로 설정)
n_subject = len(pilot_data)
n_dim_of_vector = 300

except_words = []

# word_columns를 생성
word_columns = []
for seed_word in seed_words:
    word_columns.extend([seed_word + str(i) for i in range(1, n_respond_words + 1)])

# 피험자와 단어 열을 반복하면서 처리
for i_subject in range(n_subject):
    for column in word_columns:
        response_word = pilot_data.iloc[i_subject][column]
        
        # 공백 제거
        if isinstance(response_word, str):
            response_word = response_word.strip()
        
            # 특수 문자 제거
            response_word = re.sub('[^\w\s]', '', response_word)
            
            # 소문자로 변환
            response_word = response_word.lower()
            
            ## exceptional cases
            # typo
            if 'wamrth' in response_word:
                response_word = response_word.replace('wamrth', 'warmth')
            if 'doir' in response_word:
                response_word = response_word.replace('doir', 'door')
            if 'nneck' in response_word:
                response_word = response_word.replace('nneck', 'neck')
            if 'locok' in response_word:
                response_word = response_word.replace('locok', 'lock')
            if 'sald' in response_word:
                response_word = response_word.replace('sald', 'said')
            if 'architecht' in response_word:
                response_word = response_word.replace('architecht', 'architect')
            if 'tattoes' in response_word:
                response_word = response_word.replace('tattoes', 'tattoo')
            if 'horrer' in response_word:
                response_word = response_word.replace('horrer', 'horror')
            if 'sissors' in response_word:
                response_word = response_word.replace('sissors', 'scissors')
            if 'estethician' in response_word:
                response_word = response_word.replace('estethician', 'esthetician')
            if 'breakfeasr' in response_word:
                response_word = response_word.replace('breakfeasr', 'breakfast')
            if 'quickl' in response_word:
                response_word = response_word.replace('quickl', 'quickly')
            if 'tohether' in response_word:
                response_word = response_word.replace('tohether', 'together')
            if 'watermelom' in response_word:
                response_word = response_word.replace('watermelom', 'watermelon')
            if 'dollard' in response_word:
                response_word = response_word.replace('dollard', 'dollar')
            if 'togethere' in response_word:
                response_word = response_word.replace('togethere', 'together')
            if 'favourite' in response_word:
                response_word = response_word.replace('favourite', 'favorite')
            if 'establisjed' in response_word:
                response_word = response_word.replace('establisjed', 'established')
            if 'groeries' in response_word:
                response_word = response_word.replace('groeries', 'groceries')
            if 'reaad' in response_word:
                response_word = response_word.replace('reaad', 'read')
            if 'peoplr' in response_word:
                response_word = response_word.replace('peoplr', 'people')
            if 'perspm' in response_word:
                response_word = response_word.replace('perspm', 'person')
            if 'Protecter' in response_word:
                response_word = response_word.replace('Protecter', 'protector')
            if 'grey' in response_word:
                response_word = response_word.replace('grey', 'gray')
            if 'colour' in response_word:
                response_word = response_word.replace('colour', 'color')
            if 'comepression' in response_word:
                response_word = response_word.replace('comepression', 'compression')
            if 'defenitly' in response_word:
                response_word = response_word.replace('defenitly', 'definitely')
            if 'refress' in response_word:
                response_word = response_word.replace('refress', 'refresh')
            if 'enlighted' in response_word:
                response_word = response_word.replace('enlighted', 'enlightened')
            if 'claustophobia' in response_word:
                response_word = response_word.replace('claustophobia', 'claustrophobia')
            if 'knwedge' in response_word:
                response_word = response_word.replace('knwedge', 'knowledge')
            if 'biscute' in response_word:
                response_word = response_word.replace('biscute', 'biscuit')
            if 'anethestize' in response_word:
                response_word = response_word.replace('anethestize', 'anesthetize')
            if 'graiter' in response_word:
                response_word = response_word.replace('graiter', 'grater')
            if 'blavk' in response_word:
                response_word = response_word.replace('blavk', 'black')
            if 'tastie' in response_word:
                response_word = response_word.replace('tastie', 'tasty')
            if 'storu' in response_word:
                response_word = response_word.replace('storu', 'story')
            if 'anticonvulsion' in response_word:
                response_word = response_word.replace('anticonvulsion', 'anticonvulsant')
            if 'dective' in response_word:
                response_word = response_word.replace('dective', 'detective')
            if 'jamocha' in response_word:
                response_word = response_word.replace('jamocha', 'mocha')
            if 'downa' in response_word:
                response_word = response_word.replace('downa', 'down')
            if 'relationshi' in response_word:
                response_word = response_word.replace('relationshi', 'relationship')
            if 'relationshipp' in response_word:
                response_word = response_word.replace('relationshipp', 'relationship')
            if 'qulity' in response_word:
                response_word = response_word.replace('qulity', 'quilty')
            if 'eair' in response_word:
                response_word = response_word.replace('eair', 'ear')
            if 'scine' in response_word:
                response_word = response_word.replace('scine', 'scene')
            if 'frute' in response_word:
                response_word = response_word.replace('frute', 'fruit')
            if 'gleeam' in response_word:
                response_word = response_word.replace('gleeam', 'gleam')
            if 'ebil' in response_word:
                response_word = response_word.replace('ebil', 'evil')
            if 'liness' in response_word:
                response_word = response_word.replace('liness', 'lines')
            if 'casion' in response_word:
                response_word = response_word.replace('casion', 'casino')
            if 'lonelines' in response_word:
                response_word = response_word.replace('lonelines', 'loneliness')
            if 'occasino' in response_word:
                response_word = response_word.replace('occasino', 'occasion')





            ## city, brand, name
            if 'zurich' in response_word:
                response_word = response_word.replace('zurich', 'Zurich')
            if 'madagascar' in response_word:
                response_word = response_word.replace('madagascar', 'Madagascar')
            if 'eiffel tower' in response_word:
                response_word = response_word.replace('eiffel tower', 'Eiffel_Tower')
            if 'sagrada familia' in response_word:
                response_word = response_word.replace('sagrada familia', 'Sagrada_Familia')
            if 'notredame cathedral' in response_word:
                response_word = response_word.replace('notredame cathedral', 'Notre_Dame')
            if 'montmartre' in response_word:
                response_word = response_word.replace('montmartre', 'Montmartre')
            if 'versailles palace' in response_word:
                response_word = response_word.replace('versailles palace', 'Versailles_Palace')
            if 'parthenon' in response_word:
                response_word = response_word.replace('parthenon', 'Parthenon')
            if 'sydney harbour bridg' in response_word:
                response_word = response_word.replace('sydney harbour bridg', 'Sydney Harbour_Bridge')
                response_word = response_word.replace('sydney harbour bridge', 'Sydney Harbour_Bridge')
            if 'trevi fountain' in response_word:
                response_word = response_word.replace('trevi fountain', 'Trevi_fountain')
            if 'bondi beach' in response_word:
                response_word = response_word.replace('bondi beach', 'Bondi_beach')
            if 'machu picchu' in response_word:
                response_word = response_word.replace('machu picchu', 'Machu_Picchu')
            if 'yosemite' in response_word:
                response_word = response_word.replace('yosemite national pa', 'Yosemite')
                response_word = response_word.replace('yosemite national park', 'Yosemite')
                response_word = response_word.replace('yosemite', 'Yosemite')
            if 'yellowstone national' in response_word:
                response_word = response_word.replace('yellowstone national', 'Yellowstone')
            if 'santorini' in response_word:
                response_word = response_word.replace('santorini', 'Santorini')
            if 'tahiti' in response_word:
                response_word = response_word.replace('tahiti', 'Tahiti')
            if 'bitcoin' in response_word:
                response_word = response_word.replace('bitcoin', 'Bitcoin')
            if 'buckingham palace' in response_word:
                response_word = response_word.replace('buckingham palace', 'Buckingham_palace')
            if 'stonehenge' in response_word:
                response_word = response_word.replace('stonehenge', 'Stonehenge')
            if 'tiktok' in response_word:
                response_word = response_word.replace('tiktok', 'TikTok')
            if 'champsélysées' in response_word:
                response_word = response_word.replace('champsélysées', 'Champs_Élysées')
            if 'saintechapelle' in response_word:
                response_word = response_word.replace('saintechapelle', 'Sainte_Chapelle')
            if 'giza' in response_word:
                response_word = response_word.replace('pyramids of giza', 'Giza_pyramids')
                response_word = response_word.replace('pyramids giza', 'Giza_pyramids')
            if 'ponte vecchio' in response_word:
                response_word = response_word.replace('ponte vecchio', 'Ponte_Vecchio')
            if 'rio de janeiro' in response_word:
                response_word = response_word.replace('rio de janeiro', 'Rio_de_Janeiro')
            if 'hagia sophia' in response_word:
                response_word = response_word.replace('hagia sophia', 'Hagia_Sophia')
            if 'taronga zoo' in response_word:
                response_word = response_word.replace('taronga zoo', 'Taronga_Zoo')
            if 'Snoqualmie falls' in response_word:
                response_word = response_word.replace('Snoqualmie falls', 'Snoqualmie_Falls')
            if 'stratforduponavon' in response_word:
                response_word = response_word.replace('stratforduponavon', 'Stratford')
            if 'carpeltunnel' in response_word:
                response_word = response_word.replace('carpeltunnel', 'Carpal_Tunnel')
            if 'romeo juliets b' in response_word:
                response_word = response_word.replace('romeo juliets b', 'Romeo_Juliet')
            if 'romeo and juliets b' in response_word:
                response_word = response_word.replace('romeo and juliets b', 'Romeo_Juliet')
            if 'tinsletown' in response_word:
                response_word = response_word.replace('tinsletown', 'Tinsletown')
            if 'teton national park' in response_word:
                response_word = response_word.replace('teton national park', 'Grand_Teton')
            if 'instagram' in response_word:
                response_word = response_word.replace('instagram', 'Instagram')
            if 'tarzan' in response_word:
                response_word = response_word.replace('tarzan', 'Tarzan')
            if 'moorea' in response_word:
                response_word = response_word.replace('moorea', 'Moorea')
            if 'whitsunday islands' in response_word:
                response_word = response_word.replace('whitsunday islands', 'Whitsunday_islands')
            if 'alaskadenali nation' in response_word:
                response_word = response_word.replace('alaskadenali nation', 'Denali')
            if 'snoqualmie falls' in response_word:
                response_word = response_word.replace('snoqualmie falls', 'Snoqualmie_Falls')
            if 'alcatraz island' in response_word:
                response_word = response_word.replace('alcatraz island', 'Alcatraz_Island')
            if 'french polynhesia' in response_word:
                response_word = response_word.replace('french polynhesia', 'French_Polynesia')
            if 'french polynesia' in response_word:
                response_word = response_word.replace('french polynesia', 'French_Polynesia')
            if 'barbados' in response_word:
                response_word = response_word.replace('barbados', 'Barbados')
            if 'kinkaku' in response_word:
                response_word = response_word.replace('kinkaku', 'Kinkaku')
            if 'yangon' in response_word:
                response_word = response_word.replace('yangon', 'Yangon')
            if 'vinales valley' in response_word:
                response_word = response_word.replace('vinales valley', 'Viñales')
            if 'gullfoss waterfall' in response_word:
                response_word = response_word.replace('gullfoss waterfall', 'Gullfoss')
            if 'niagaraonthelake' in response_word:
                response_word = response_word.replace('niagaraonthelake', 'Niagara')
            if 'athabasca falls' in response_word:
                response_word = response_word.replace('athabasca falls', 'Athabasca')
            if 'banff national park' in response_word:
                response_word = response_word.replace('banff national park', 'Banff')
            if 'bathsheba beach' in response_word:
                response_word = response_word.replace('bathsheba beach', 'Bathsheba')
            if 'burj khalifa' in response_word:
                response_word = response_word.replace('burj khalifa', 'Burj_Khalifa')
            if 'shwedagon pagoda' in response_word:
                response_word = response_word.replace('shwedagon pagoda', 'Shwedagon_Pagoda')
            if 'stmarks square' in response_word:
                response_word = response_word.replace('stmarks square', 'San_Marcos')

            ## need to be splited
            if 'stormcloud' in response_word:
                response_word = response_word.replace('stormcloud', 'storm cloud')
            if 'didnt you' in response_word:
                response_word = response_word.replace('didnt you', 'did not you')
            if 'aint easy' in response_word:
                response_word = response_word.replace('aint easy', 'not easy')
            if 'goodtimes' in response_word:
                response_word = response_word.replace('goodtimes', 'good time')
            if 'slowmotion' in response_word:
                response_word = response_word.replace('slowmotion', 'slow motion')
            if 'lightnight' in response_word:
                response_word = response_word.replace('lightnight', 'light night')
            
            
            if 'bravetart' in response_word:
                response_word = response_word.replace('bravetart', 'tart')
            if 'shart' in response_word:
                response_word = response_word.replace('shart', 'shit fart')
            if 'twix' in response_word:
                response_word = response_word.replace('twix', 'chocolate bar')
            if 'reeses' in response_word:
                response_word = response_word.replace('reeses', 'chocolate candy')
            if 'for 12 hours' in response_word:
                response_word = response_word.replace('for 12 hours', 'twelve hours')
            if 'unckle also' in response_word:
                response_word = response_word.replace('unckle also', 'uncle')
            if 'spiney' in response_word:
                response_word = response_word.replace('spiney', 'cactus spine')
            if 'uluru' in response_word:
                response_word = response_word.replace('uluru', 'Ayers rock')
            if 'that i go to and enj' in response_word:
                response_word = response_word.replace('that i go to and enj', 'go enjoy')
            if 'fishermans wharf' in response_word:
                response_word = response_word.replace('fishermans wharf', 'fishermen wharf')
            if 'blue domes in oia' in response_word:
                response_word = response_word.replace('blue domes in oia', 'blue dome Santorini')
            if 'david by michelangel' in response_word:
                response_word = response_word.replace('david by michelangel', 'David Michelangelo')

            ## missing
            if 'boken' in response_word:
                response_word = response_word.replace('boken', '')
            if 'siun' in response_word:
                response_word = response_word.replace('siun', '')
            if 'raysd' in response_word:
                response_word = response_word.replace('raysd', '')
            if 'klaw' in response_word:
                response_word = response_word.replace('klaw', '')
            if 'wose' in response_word:
                response_word = response_word.replace('wose', '')
            if 'stroom' in response_word:
                response_word = response_word.replace('stroom', '')
            if 'appleseed' in response_word:
                response_word = response_word.replace('appleseed', '')
            if 'agiab' in response_word:
                response_word = response_word.replace('agiab', '')
            if 'thornberrys' in response_word:
                response_word = response_word.replace('thornberrys', '')
            if 'cartman' in response_word:
                response_word = response_word.replace('cartman', '')
            if '1907' in response_word:
                response_word = response_word.replace('1907', '')
            if 'gena' in response_word:
                response_word = response_word.replace('gena', '')
            if 'balf' in response_word:
                response_word = response_word.replace('balf', '')
            if 'suice' in response_word:
                response_word = response_word.replace('suice', '')
            if 'la2a' in response_word:
                response_word = response_word.replace('la2a', '')
            if 'siscuss' in response_word:
                response_word = response_word.replace('siscuss', '')
            if 'shope' in response_word:
                response_word = response_word.replace('shope', '')
            if 'pultec' in response_word:
                response_word = response_word.replace('pultec', '') # word2vec에 없음
            if 'mount otemanu' in response_word:
                response_word = response_word.replace('mount otemanu', '') # word2vec에 없음
            if 'the globe theatre' in response_word:
                response_word = response_word.replace('the globe theatre', '') # word2vec에 없음
            if 'forum romanum' in response_word:
                response_word = response_word.replace('forum romanum', '') # word2vec에 없음
            if 'kenji lopezalt' in response_word:
                response_word = response_word.replace('kenji lopezalt', '') # word2vec에 없음
            if 'arbys' in response_word:
                response_word = response_word.replace('arbys', '') # word2vec에 없음
            if 'Kinkaku' in response_word:
                response_word = response_word.replace('Kinkaku', '') # word2vec에 없음

            response_words = response_word.split()
            response_words = [word for word in response_words if word not in ['is', 'a','to','of','and']]

            for i_el in range( len(response_words) ):
                try:
                    vec_word2vec_in = word2vec_model[response_words[i_el]]
                except:
                    except_word = {
                        'Prolific_ID': pilot_data.iloc[i_subject]['Prolific_ID'],
                        'subject': pilot_data.iloc[i_subject]['subject'],
                        'category': column,
                        'word': response_word
                    }
                    except_words.append(except_word)

        # 수정된 단어를 새로운 데이터프레임에 할당
        processed_data.at[i_subject, column] = response_word

In [186]:
processed_data

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,friend21,friend22,friend23,friend24,friend25,friend26,friend27,friend28,friend29,friend30
0,5d53bffa147a7d00015aae5a,1,door,gate,outside,grass,itchy,rash,chicken pox,shingles,...,burned down,scary,movies,knocked up,Tinsletown,christmas tree,holiday,decorate,fun,party
1,5f00ec86304f7322eb8dfa41,2,unlock,door,enter,dreams,time and space,possibilites,infinite,time,...,transparent,glass,shattered,repair,meaningful,bond,glue,all together,matters,wonders
2,5de27ced22383629b807cc70,3,hole,ground,hog,pig,pork,said,dressing,clothes,...,sunshine,warmth,blanket,heavy,body,muscle,protein,shake,dance,jump
3,5f121091e95fdc03b5e897d0,4,card,birthday,song,music,radio,football,sunday,church,...,woman,hair,brush,pony,race,win,lose,game,pest,sad
4,633f46f05bc4c6198322424a,5,lock,door,knob,metal,material,paper,tree,roots,...,pillow,soft,hard,rock,stone,mineral,chemical,artificial,fake,false
5,58380cb9f1faf8000129673a,6,door,house,farm,growth,society,culture,people,humans,...,banks,smartphones,light,apple,virtual reality,video games,controllers,tv,monitor,home
6,5d8a29c082fec30001d9c24a,7,lock,spin,around,turn,look,live,like,sound,...,serum,new,nose,noggin,quilt,quake,shun,salt,yours,yank
7,5ca6046dbbb3040012c2ba7d,8,lock,door,open,close,window,cold,air,fan,...,amusement,laughter,crying,emotion,dull,hurt,pain,wrist,Carpal_Tunnel,stretch
8,64018f4d1a16dfe2b0f7c552,9,board,game,boy,girl,friend,enemy,red,flag,...,dolphin,breathing,heavily,sighing,yawning,tired,bed,home,room,comfort
9,6172b88315142e4eaa555c95,10,new york city,brooklyn bridge,paris,Eiffel_Tower,rome,colosseum,london,big ben,...,times square,central park,empire state buildin,wall street,brooklyn bridge,museum,broadway,central park zoo,paris,Eiffel_Tower
10,5a1b51e59b760100013a85d3,11,lock,door,house,window,panel,green,nature,grass,...,shot,spy,detective,study,school,college,library,books,red,yellow
11,5ffd530863b06e2247f69652,12,stone,wood,shingles,on a roof,standing,in the street,making moves,to the cash,...,dime,strong,ways,to make,money,is easy,just manage,your time,well,you will
12,6102053795bd9b55ab979a48,13,gold,silver,necklace,pearl,white,soft,skin,touch,...,flat,calm,nighttime,gown,candle,window,still,frozen,movie,shrek
13,614ee5e28a2f0a07d4d639dd,14,key,key,key,key,key,key,key,god,...,key,board,mobile,computer,dairy,pant,show,,grass,biscuit
14,627e7b6d33e1df14160c05ba,15,lock,door,wood,tree,candle,wick,burn,fire,...,story,book,fiction,life,living,death,sleep,gone,forever,always
15,5cab944b41de360017e2c3db,16,lock,password,security,safe,home,family,sister,female,...,bright,happy,mood,happy,peace,calm,content,beautiful,music,song
16,5930c7fdfa699e0001017cc1,17,hole,puncher,face,cream,cheese,grater,nail,biter,...,music,guitar,with the band,shows,at the town,and the crowd,cheering on,lettuce,in the garden,with tomatoes
17,611e64ad7ea7083dd09ce1dc,18,ellis island,hudson river,albany,times square,broadway,central park,brooklyn bridge,empire state buildin,...,san juan islands,space needle,olympic national par,mount rainier,pike place market,Snoqualmie_Falls,mount vernon estate,great barrier reef,ayers rock,sydney opera house
18,5bfadc1846911f0001d7d1eb,19,lock,door,house,living,people,humans,irrational,silly,...,treatment,caregiver,good,positive,helper,nice,humane,worker,technician,cheese
19,5c82c9a4d8302a00010639b8,20,door,lock,key,safe,money,time,effort,greed,...,twitter,youtube,video,content,mood,health,aware,skin,bones,blood
20,5b8e11444cd6dd0001bf07d9,21,door,locked,outside,homeless,tent,cold,snow,ice,...,given,fun,laugh,spend,afternoon,house,best,joy,blessed,talk
21,64135e3d9cd5e3f16290d29c,22,lime,pie,apple,pear,apple,dog,cat,china,...,soda,sprite,cola,maid,bed,cook,chicken,breast,grill,soup
22,616d09161d975b379aa79f99,23,word,over,bearing,babies,are cute,here,ing,rain,...,food,yes,to what,friendship,flows,smoothly,always,the best,is here,presently
23,62e19208352cd518d7b2f085,24,door,knob,peep hole,knock,open,close,welcome,doorbell,...,feeling,mentality,considerate,helpful,handy,caring,giving,appreciative,gift,treasure
24,6108564a9fa80b278d0f0042,25,trail,tree,car,race,track,train,fast,speed,...,store,purchase,order,wait,walk,time,fast,patient,loud,books
25,5edb487096035b7c2ab90276,26,hole,see,through,enter,forward,move,speed,fas,...,iron,armor,impenetrable,shield,protect,defense,strong,unique,one,many
26,627a9c07dd6b4cb9de3a9222,27,door,bell,christmas,tree,green,grass,flower,petals,...,snow,cold,water,bath,soap,clean,spring,walking,relaxed,asleep
27,6400e20ccc1ad6bc03657358,28,lock,bedroom,bed,covers,sheets,bear,cuddle,alone,...,antipsychotic,anticonvulsant,rubber,malleable,iron,stiff,rigid,rugged,resolve,stout
28,5d332957d0635b00013bd785,29,lock,key,home,safe,love,happiness,mood,sadness,...,merry,christmas,gifts,money,work,time,wasted,misused,useless,pointless
29,5c7ecfbb4243370001ed2f0e,30,door,knob,golden,brass,locket,diary,writing,journalism,...,unfair,unjust,unhappy,mad,sad,angry,depressed,anxious,scared,annoyed
30,5d847ac9be4b0b00188463d7,31,lock,door,window,building,city,highrise,skyline,storm cloud,...,doctor,professional,calculated,project,business,spreadsheet,performance,spectacle,showman,magician
31,630d941b48a1bf15ca5ade75,32,door,room,floor,carpet,house,yard,grass,green,...,bliss,ignorance,frail,weak,strong,good,strength,good,knowledge,doe
32,5f88877885e51d02acd71b12,33,door,house,home,family,children,mother,father,work,...,table,book,air,jump,cat,dock,dog,knock,creep,maple
33,6154973c69da7c97996a19f6,34,lock,safe,home,family,tree,fruit,smoothie,nutrients,...,crowded,claustrophobia,phobia,anxiety,depression,therapy,talking,social,gathering,food
34,5f91a6bf59acc003a749718a,35,open,door,lock,house,frame,gentle,play,game,...,states,site,harrow,trick,tent,shallow,sorry,chair,true,great
35,5d092069fb1a540001dd5028,36,lock,door,home,life,place,living,habitat,place,...,body,soul,interest,intrigue,mystery,hunt,wolf,instinct,intuition,logic
36,5f49f3262a3d07563d14a7f1,37,lock,door,wood,tree,roots,grass,land,earth,...,faith,trust,home,safety,security,steadiness,steady,stable,freedom,roam
37,5c9e89d950dde20001ce12b3,38,chain,neck,neck,arm,legs,face,tattoo,models,...,africa,south africa,ethiopia,kenya,nairobi,skiing,rollercoaster,disney,world,time
38,60bea11ea6e2371d747c5d1d,39,open,up,high,heels,walk,run,farm,fun,...,loaf,hand,handed,palm,potent,potion,health,gut,stomach,clear
39,63f78ac7f848808e761fbb0f,40,to unlock,the door,for security,of house,and sleep well,after a long day,at work,for survival,...,right,cry,laugh,madam,sir,king,london,country,welcome,handsome
40,60c18d0606115c8eecb6091b,41,house,home,dog,cat,pet,home,bills,money,...,dress,purse,white,gates,rich,cars,mansion,lion,zoo,elephant
41,610508c09d61c098f072605b,42,hole,floor,roof,house,built,architect,career,job,...,long,recognize,hi,me,how,you,doing,bald,pluck,sober
42,62fb383ce16d6921d1c2c2b8,43,door,knob,light,bulb,,,dan,dam,...,interesting,hope,good,happy,dump,live,enjoyment,sober,happy,souls
43,615e1782e969d4939045c54f,44,door,,broken,fast,tun,run,jump,close,...,travel,vacation,house,marry,close,,trials,ups,down,respite
44,62a2adb16716c2e0c8d3c07a,45,house,safe,content,happy,mental,human,earth,community,...,street,car,fast,lights,bright,street lamp,dim,dark,moon,universe
45,5f46d1d7d38a210aa8ca0eb8,46,lock,unlock,door,window,mac,apple,banana,orange,...,crime,police,officer,fire,water,earth,air,bender,metal,plastic
46,602c5fd808e6c3528a8ba43b,47,to the city,we enter,but with no weapons,we cannot fight,without peace,there is only war,in the future,there are none,...,mirror,self,body,person,identity,history,memory,recall,war,fight
47,6234965d3869b875dc31d93a,48,club,diamond,hands,wash,room,bed,blanket,warm,...,rock,deep rock galactic,karl,junior,hamburger,shake,mocha,,horsey sauce,reuben
48,5d2df867d7cc160019673031,49,lock,gate,entrance,home,food,eating,table,sitting,...,everybody watch,surley,one day i can do,yah its true,i killed,my,enemy,in my,entire family,frond
49,5dd4074feab0423daf012f92,50,lock,hair,cut,scissors,craft,art,paint,color,...,sleep,morning,alarm,awake,sun,sunrise,coffee,eggs,bacon,tea
50,57dd186e6598aa0001992616,51,lock,door,handle,turn,knob,hole,dirt,ground,...,water,cool,refreshing,soothing,chill,relaxing,prop feet up,ice,cream,lotion
51,63dd3dd2593c92be97d8dbde,52,hole,pit,hill,ant,bug,bee,hive,honey,...,king,crown,head,neck,body,arms,hand,fingers,point,map
52,5e4e844553bc702cdf68404d,53,door,room,furniture,chair,pillow,bed,sleep,night,...,space,shelves,books,library,knowledge,power,leader,team,job,money
53,5e6ec2818808e6486e268039,54,lock,door,wood,fire,hydrant,street,car,stop,...,red,hair,salon,nails,long,bored,fidget,toy,animal,zoo
54,56ec9fa4f9ffc4000ac1941b,55,room,library,books,table,chairs,sitting,butt,round,...,light night,shock,tornado,spin,sonic,fast food,mcdonalds,burger king,big mac,whopper
55,5f6f738fef894f0dbf9839f8,56,door,lock,lock,house,people,alive,animal,dog,...,england,united kingdom,king,monarch,absolute rule,dictatorship,north korea,nuclear weapons,united states,power
56,5c560b6fccb08c0001e134a8,57,hole,open,door,frame,picture,beauty,eyes,blue,...,farm,nachos,food,camping,marshmallow,fire,camping,wood,burn,amber
57,610f615654fdbcac0f485a9d,58,lock,door,house,roof,tin,man,woman,girl,...,halloween,ghost,dead,grave,scary,pumpkin,skeleton,bones,dog,puppy

In [188]:
except_words

[]

In [189]:
pd.DataFrame(except_words).to_csv(pilot2_dir + '/need_to_be_fixed.csv')