# response words check

word2vec 사전에 없는 단어들을 걸러내는 코드입니다. \
이후 수동으로 전처리 작업에 추가할 예정입니다. 결과는 need_to_be_fixed.csv 파일에서 확인할 수 있습니다.

In [150]:
import os
import re

import pandas as pd
from gensim.models import KeyedVectors

In [151]:
pilot2_dir = os.getcwd()

# word2vec model 로딩
word2vec_model = KeyedVectors.load_word2vec_format(pilot2_dir + '/../pretrained/GoogleNews-vectors-negative300.bin', binary=True)

In [152]:
processed_data_dir = os.getcwd() + '/data/processed/' # data위치 지정

pilot_data = pd.read_csv(processed_data_dir + 'merged_data.csv')
pilot_data[0:3]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,friend21,friend22,friend23,friend24,friend25,friend26,friend27,friend28,friend29,friend30
0,5d53bffa147a7d00015aae5a,1,Door,Gate,Outside,Grass,Itchy,Rash,Chicken pox,Shingles,...,Burned down,Scary,Movies,Knocked up,Tinsletown,Christmas tree,Holiday,Decorate,Fun,Party
1,5f00ec86304f7322eb8dfa41,2,Unlock,Door,Enter,Dreams,Time and space,Possibilites,Infinite,Time,...,Transparent,Glass,Shattered,Repair,Meaningful,Bond,Glue,All together,Matters,Wonders
2,5de27ced22383629b807cc70,3,Hole,Ground,Hog,Pig,Pork,Sald,Dressing,Clothes,...,Sunshine,Wamrth,Blanket,Heavy,Body,Muscle,Protein,Shake,Dance,Jump

In [153]:
# 기존 데이터프레임을 복사하여 새로운 데이터프레임 생성
processed_data = pilot_data.copy()

# seed_words와 n_respond_words를 정의
seed_words = ['key', 'money', 'friend']
n_respond_words = 30

# 피험자 수와 차원을 설정 (실제 데이터에 따라 적절한 값으로 설정)
n_subject = len(pilot_data)
n_dim_of_vector = 300

except_words = []

# word_columns를 생성
word_columns = []
for seed_word in seed_words:
    word_columns.extend([seed_word + str(i) for i in range(1, n_respond_words + 1)])

# 피험자와 단어 열을 반복하면서 처리
for i_subject in range(n_subject):
    for column in word_columns:
        response_word = pilot_data.iloc[i_subject][column]
        
        # 공백 제거
        if isinstance(response_word, str):
            response_word = response_word.strip()
        
            # 특수 문자 제거
            response_word = re.sub('[^\w\s]', '', response_word)
            
            # 소문자로 변환
            response_word = response_word.lower()
            
            ## exceptional cases
            # typo
            if 'wamrth' in response_word:
                response_word = response_word.replace('wamrth', 'warmth')
            if 'doir' in response_word:
                response_word = response_word.replace('doir', 'door')
            if 'nneck' in response_word:
                response_word = response_word.replace('nneck', 'neck')
            if 'locok' in response_word:
                response_word = response_word.replace('locok', 'lock')
            if 'sald' in response_word:
                response_word = response_word.replace('sald', 'said')
            if 'architecht' in response_word:
                response_word = response_word.replace('architecht', 'architect')
            if 'tattoes' in response_word:
                response_word = response_word.replace('tattoes', 'tattoo')
            if 'horrer' in response_word:
                response_word = response_word.replace('horrer', 'horror')
            if 'sissors' in response_word:
                response_word = response_word.replace('sissors', 'scissors')
            if 'estethician' in response_word:
                response_word = response_word.replace('estethician', 'esthetician')
            if 'breakfeasr' in response_word:
                response_word = response_word.replace('breakfeasr', 'breakfast')
            if 'quickl' in response_word:
                response_word = response_word.replace('quickl', 'quickly')
            if 'tohether' in response_word:
                response_word = response_word.replace('tohether', 'together')
            if 'watermelom' in response_word:
                response_word = response_word.replace('watermelom', 'watermelon')
            if 'dollard' in response_word:
                response_word = response_word.replace('dollard', 'dollar')
            if 'togethere' in response_word:
                response_word = response_word.replace('togethere', 'together')
            if 'favourite' in response_word:
                response_word = response_word.replace('favourite', 'favorite')
            if 'establisjed' in response_word:
                response_word = response_word.replace('establisjed', 'established')
            if 'groeries' in response_word:
                response_word = response_word.replace('groeries', 'groceries')
            if 'reaad' in response_word:
                response_word = response_word.replace('reaad', 'read')
            if 'peoplr' in response_word:
                response_word = response_word.replace('peoplr', 'people')
            if 'perspm' in response_word:
                response_word = response_word.replace('perspm', 'person')
            if 'Protecter' in response_word:
                response_word = response_word.replace('Protecter', 'protector')
            if 'grey' in response_word:
                response_word = response_word.replace('grey', 'gray')
            if 'colour' in response_word:
                response_word = response_word.replace('colour', 'color')
            if 'comepression' in response_word:
                response_word = response_word.replace('comepression', 'compression')
            if 'defenitly' in response_word:
                response_word = response_word.replace('defenitly', 'definitely')
            if 'refress' in response_word:
                response_word = response_word.replace('refress', 'refresh')
            if 'enlighted' in response_word:
                response_word = response_word.replace('enlighted', 'enlightened')
            if 'claustophobia' in response_word:
                response_word = response_word.replace('claustophobia', 'claustrophobia')
            if 'knwedge' in response_word:
                response_word = response_word.replace('knwedge', 'knowledge')
            if 'biscute' in response_word:
                response_word = response_word.replace('biscute', 'biscuit')
            if 'anethestize' in response_word:
                response_word = response_word.replace('anethestize', 'anesthetize')
            if 'graiter' in response_word:
                response_word = response_word.replace('graiter', 'grater')
            if 'blavk' in response_word:
                response_word = response_word.replace('blavk', 'black')
            if 'tastie' in response_word:
                response_word = response_word.replace('tastie', 'tasty')
            if 'storu' in response_word:
                response_word = response_word.replace('storu', 'story')
            if 'anticonvulsion' in response_word:
                response_word = response_word.replace('anticonvulsion', 'anticonvulsant')
            if 'dective' in response_word:
                response_word = response_word.replace('dective', 'detective')
            if 'jamocha' in response_word:
                response_word = response_word.replace('jamocha', 'mocha')
            if 'downa' in response_word:
                response_word = response_word.replace('downa', 'down')
            if 'relationshi' in response_word:
                response_word = response_word.replace('relationshi', 'relationship')
            if 'relationshipp' in response_word:
                response_word = response_word.replace('relationshipp', 'relationship')
            if 'qulity' in response_word:
                response_word = response_word.replace('qulity', 'quilty')
            if 'eair' in response_word:
                response_word = response_word.replace('eair', 'ear')
            if 'scine' in response_word:
                response_word = response_word.replace('scine', 'scene')
            if 'frute' in response_word:
                response_word = response_word.replace('frute', 'fruit')
            if 'gleeam' in response_word:
                response_word = response_word.replace('gleeam', 'gleam')
            if 'ebil' in response_word:
                response_word = response_word.replace('ebil', 'evil')
            if 'liness' in response_word:
                response_word = response_word.replace('liness', 'lines')
            if 'casion' in response_word:
                response_word = response_word.replace('casion', 'casino')
            if 'lonelines' in response_word:
                response_word = response_word.replace('lonelines', 'loneliness')
            if 'occasino' in response_word:
                response_word = response_word.replace('occasino', 'occasion')





            ## city, brand, name
            if 'zurich' in response_word:
                response_word = response_word.replace('zurich', 'Zurich')
            if 'madagascar' in response_word:
                response_word = response_word.replace('madagascar', 'Madagascar')
            if 'eiffel tower' in response_word:
                response_word = response_word.replace('eiffel tower', 'Eiffel_Tower')
            if 'sagrada familia' in response_word:
                response_word = response_word.replace('sagrada familia', 'Sagrada_Familia')
            if 'notredame cathedral' in response_word:
                response_word = response_word.replace('notredame cathedral', 'Notre_Dame')
            if 'montmartre' in response_word:
                response_word = response_word.replace('montmartre', 'Montmartre')
            if 'versailles palace' in response_word:
                response_word = response_word.replace('versailles palace', 'Versailles_Palace')
            if 'parthenon' in response_word:
                response_word = response_word.replace('parthenon', 'Parthenon')
            if 'sydney harbour bridg' in response_word:
                response_word = response_word.replace('sydney harbour bridg', 'Sydney Harbour_Bridge')
                response_word = response_word.replace('sydney harbour bridge', 'Sydney Harbour_Bridge')
            if 'trevi fountain' in response_word:
                response_word = response_word.replace('trevi fountain', 'Trevi_fountain')
            if 'bondi beach' in response_word:
                response_word = response_word.replace('bondi beach', 'Bondi_beach')
            if 'machu picchu' in response_word:
                response_word = response_word.replace('machu picchu', 'Machu_Picchu')
            if 'yosemite' in response_word:
                response_word = response_word.replace('yosemite national pa', 'Yosemite')
                response_word = response_word.replace('yosemite national park', 'Yosemite')
                response_word = response_word.replace('yosemite', 'Yosemite')
            if 'yellowstone national' in response_word:
                response_word = response_word.replace('yellowstone national', 'Yellowstone')
            if 'santorini' in response_word:
                response_word = response_word.replace('santorini', 'Santorini')
            if 'tahiti' in response_word:
                response_word = response_word.replace('tahiti', 'Tahiti')
            if 'bitcoin' in response_word:
                response_word = response_word.replace('bitcoin', 'Bitcoin')
            if 'buckingham palace' in response_word:
                response_word = response_word.replace('buckingham palace', 'Buckingham_palace')
            if 'stonehenge' in response_word:
                response_word = response_word.replace('stonehenge', 'Stonehenge')
            if 'tiktok' in response_word:
                response_word = response_word.replace('tiktok', 'TikTok')
            if 'champsélysées' in response_word:
                response_word = response_word.replace('champsélysées', 'Champs_Élysées')
            if 'saintechapelle' in response_word:
                response_word = response_word.replace('saintechapelle', 'Sainte_Chapelle')
            if 'giza' in response_word:
                response_word = response_word.replace('pyramids of giza', 'Giza_pyramids')
                response_word = response_word.replace('pyramids giza', 'Giza_pyramids')
            if 'ponte vecchio' in response_word:
                response_word = response_word.replace('ponte vecchio', 'Ponte_Vecchio')
            if 'rio de janeiro' in response_word:
                response_word = response_word.replace('rio de janeiro', 'Rio_de_Janeiro')
            if 'hagia sophia' in response_word:
                response_word = response_word.replace('hagia sophia', 'Hagia_Sophia')
            if 'taronga zoo' in response_word:
                response_word = response_word.replace('taronga zoo', 'Taronga_Zoo')
            if 'Snoqualmie falls' in response_word:
                response_word = response_word.replace('Snoqualmie falls', 'Snoqualmie_Falls')
            if 'stratforduponavon' in response_word:
                response_word = response_word.replace('stratforduponavon', 'Stratford')
            if 'carpeltunnel' in response_word:
                response_word = response_word.replace('carpeltunnel', 'Carpal_Tunnel')
            if 'romeo juliets b' in response_word:
                response_word = response_word.replace('romeo juliets b', 'Romeo_Juliet')
            if 'romeo and juliets b' in response_word:
                response_word = response_word.replace('romeo and juliets b', 'Romeo_Juliet')
            if 'tinsletown' in response_word:
                response_word = response_word.replace('tinsletown', 'Tinsletown')
            if 'teton national park' in response_word:
                response_word = response_word.replace('teton national park', 'Grand_Teton')
                
            if 'instagram' in response_word:
                response_word = response_word.replace('instagram', 'Instagram')
            if 'tarzan' in response_word:
                response_word = response_word.replace('tarzan', 'Tarzan')
            if 'moorea' in response_word:
                response_word = response_word.replace('moorea', 'Moorea')
            if 'whitsunday islands' in response_word:
                response_word = response_word.replace('whitsunday islands', 'Whitsunday_islands')
            if 'alaskadenali nation' in response_word:
                response_word = response_word.replace('alaskadenali nation', 'Denali')
            if 'snoqualmie falls' in response_word:
                response_word = response_word.replace('snoqualmie falls', 'Snoqualmie_Falls')
            if 'alcatraz island' in response_word:
                response_word = response_word.replace('alcatraz island', 'Alcatraz_Island')
            if 'french polynhesia' in response_word:
                response_word = response_word.replace('french polynhesia', 'French_Polynesia')
            if 'french polynesia' in response_word:
                response_word = response_word.replace('french polynesia', 'French_Polynesia')
            if 'barbados' in response_word:
                response_word = response_word.replace('barbados', 'Barbados')
            if 'yangon' in response_word:
                response_word = response_word.replace('yangon', 'Yangon')
            if 'vinales valley' in response_word:
                response_word = response_word.replace('vinales valley', 'Viñales')
            if 'gullfoss waterfall' in response_word:
                response_word = response_word.replace('gullfoss waterfall', 'Gullfoss')
            if 'niagaraonthelake' in response_word:
                response_word = response_word.replace('niagaraonthelake', 'Niagara')
            if 'athabasca falls' in response_word:
                response_word = response_word.replace('athabasca falls', 'Athabasca')
            if 'banff national park' in response_word:
                response_word = response_word.replace('banff national park', 'Banff')
            if 'bathsheba beach' in response_word:
                response_word = response_word.replace('bathsheba beach', 'Bathsheba')
            if 'burj khalifa' in response_word:
                response_word = response_word.replace('burj khalifa', 'Burj_Khalifa')
            if 'shwedagon pagoda' in response_word:
                response_word = response_word.replace('shwedagon pagoda', 'Shwedagon_Pagoda')
            if 'stmarks square' in response_word:
                response_word = response_word.replace('stmarks square', 'San_Marcos')
            if 'mount fuji' in response_word:
                response_word = response_word.replace('mount fuji', 'Mount_Fuji')
            if 'louvre museum' in response_word:
                response_word = response_word.replace('louvre museum', 'Louvre_Museum')
            if 'niagara falls' in response_word:
                response_word = response_word.replace('niagara falls', 'Niagara_Falls')


            ## etc
            if 'stormcloud' in response_word:
                response_word = response_word.replace('stormcloud', 'storm cloud')
            if 'didnt you' in response_word:
                response_word = response_word.replace('didnt you', 'did not you')
            if 'aint easy' in response_word:
                response_word = response_word.replace('aint easy', 'not easy')
            if 'goodtimes' in response_word:
                response_word = response_word.replace('goodtimes', 'good time')
            if 'slowmotion' in response_word:
                response_word = response_word.replace('slowmotion', 'slow motion')
            if 'lightnight' in response_word:
                response_word = response_word.replace('lightnight', 'light night')
            if 'bravetart' in response_word:
                response_word = response_word.replace('bravetart', 'tart')
            if 'shart' in response_word:
                response_word = response_word.replace('shart', 'shit fart')
            if 'twix' in response_word:
                response_word = response_word.replace('twix', 'chocolate bar')
            if 'reeses' in response_word:
                response_word = response_word.replace('reeses', 'chocolate candy')
            if 'for 12 hours' in response_word:
                response_word = response_word.replace('for 12 hours', 'twelve hours')
            if 'unckle also' in response_word:
                response_word = response_word.replace('unckle also', 'uncle')
            if 'spiney' in response_word:
                response_word = response_word.replace('spiney', 'cactus spine')
            if 'uluru' in response_word:
                response_word = response_word.replace('uluru', 'Ayers rock')
            if 'that i go to and enj' in response_word:
                response_word = response_word.replace('that i go to and enj', 'go enjoy')
            if 'fishermans wharf' in response_word:
                response_word = response_word.replace('fishermans wharf', 'fishermen wharf')
            if 'blue domes in oia' in response_word:
                response_word = response_word.replace('blue domes in oia', 'blue dome Santorini')
            if 'david by michelangel' in response_word:
                response_word = response_word.replace('david by michelangel', 'David Michelangelo')
            if 'new york city' in response_word:
                response_word = response_word.replace('new york city', 'New_York')
            if 'brooklyn bridge' in response_word:
                response_word = response_word.replace('brooklyn bridge', 'Brooklyn_Bridge')
            if 'hudson river' in response_word:
                response_word = response_word.replace('hudson river', 'Hudson_River')
            if 'for security' in response_word:
                response_word = response_word.replace('for security', 'security')
            if 'times square' in response_word:
                response_word = response_word.replace('times square', 'Times_Square')
            if 'central park' in response_word:
                response_word = response_word.replace('central park', 'park') # word2vec에 없음
            if 'making moves' in response_word:
                response_word = response_word.replace('making moves', 'move') 
            if 'stmarks square' in response_word:
                response_word = response_word.replace('stmarks square', 'San_Marcos')
            if 'catacombs paris' in response_word:
                response_word = response_word.replace('catacombs paris', 'Catacombs')
            if 'vatican city' in response_word:
                response_word = response_word.replace('vatican city', 'Vatican')
            if 'las vegas' in response_word:
                response_word = response_word.replace('las vegas', 'Las_Vegas')
            if 'rio negro river' in response_word:
                response_word = response_word.replace('rio negro river', 'Rio_Negro')
            if 'grand canyon nationa' in response_word:
                response_word = response_word.replace('grand canyon nationa', 'Grand_Canyon')
            if 'washington dc' in response_word:
                response_word = response_word.replace('washington dc', 'Washington_DC')
            if 'antelope canyon' in response_word:
                response_word = response_word.replace('antelope canyon', 'Antelope_Canyon')
            if 'moai statues' in response_word:
                response_word = response_word.replace('moai statues', 'Moai')
            if 'capitol hill' in response_word:
                response_word = response_word.replace('capitol hill', 'Capitol_Hill')
            if 'san francisco' in response_word:
                response_word = response_word.replace('san francisco', 'SanFrancisco')
            if 'golden gate bridge' in response_word:
                response_word = response_word.replace('golden gate bridge', 'Golden_Gate_Bridge')
            if 'kanye west' in response_word:
                response_word = response_word.replace('kanye west', 'Kanye_West')
            if 'united nations' in response_word:
                response_word = response_word.replace('united nations', 'United_Nations')
            if 'glacier national par' in response_word:
                response_word = response_word.replace('glacier national par', 'Glacier') 
            if 'oxford university' in response_word:
                response_word = response_word.replace('oxford university', 'Oxford') 
            if 'william shakespeare' in response_word:
                response_word = response_word.replace('william shakespeare', 'Shakespeare') 
            if 'sequoia national par' in response_word:
                response_word = response_word.replace('sequoia national par', 'Sequoia') 
            if 'united kingdom' in response_word:
                response_word = response_word.replace('united kingdom', 'United_Kingdom') 
            if 'south africa' in response_word:
                response_word = response_word.replace('south africa', 'South_Africa') 
            if 'pike place market' in response_word:
                response_word = response_word.replace('pike place market', 'Pike_Place') 
            if 'united states' in response_word:
                response_word = response_word.replace('united states', 'United_States') 
            if 'sydney opera house' in response_word:
                response_word = response_word.replace('sydney opera house', 'Sydney_Opera') 



            ## missing
            if 'boken' in response_word:
                response_word = response_word.replace('boken', '')
            if 'siun' in response_word:
                response_word = response_word.replace('siun', '')
            if 'raysd' in response_word:
                response_word = response_word.replace('raysd', '')
            if 'klaw' in response_word:
                response_word = response_word.replace('klaw', '')
            if 'wose' in response_word:
                response_word = response_word.replace('wose', '')
            if 'stroom' in response_word:
                response_word = response_word.replace('stroom', '')
            if 'appleseed' in response_word:
                response_word = response_word.replace('appleseed', '')
            if 'agiab' in response_word:
                response_word = response_word.replace('agiab', '')
            if 'thornberrys' in response_word:
                response_word = response_word.replace('thornberrys', '')
            if 'cartman' in response_word:
                response_word = response_word.replace('cartman', '')
            if '1907' in response_word:
                response_word = response_word.replace('1907', '')
            if 'gena' in response_word:
                response_word = response_word.replace('gena', '')
            if 'balf' in response_word:
                response_word = response_word.replace('balf', '')
            if 'suice' in response_word:
                response_word = response_word.replace('suice', '')
            if 'la2a' in response_word:
                response_word = response_word.replace('la2a', '')
            if 'siscuss' in response_word:
                response_word = response_word.replace('siscuss', '')
            if 'shope' in response_word:
                response_word = response_word.replace('shope', '')
            if 'pultec' in response_word:
                response_word = response_word.replace('pultec', '') # word2vec에 없음
            if 'mount otemanu' in response_word:
                response_word = response_word.replace('mount otemanu', '') # word2vec에 없음
            if 'the globe theatre' in response_word:
                response_word = response_word.replace('the globe theatre', '') # word2vec에 없음
            if 'forum romanum' in response_word:
                response_word = response_word.replace('forum romanum', '') # word2vec에 없음
            if 'kenji lopezalt' in response_word:
                response_word = response_word.replace('kenji lopezalt', '') # word2vec에 없음
            if 'arbys' in response_word:
                response_word = response_word.replace('arbys', '') # word2vec에 없음
            if 'empire state buildin' in response_word:
                response_word = response_word.replace('empire state buildin', 'building') # word2vec에 없음
            if 'chris rock' in response_word:
                response_word = response_word.replace('chris rock', 'actor') # word2vec에 없음
            if 'charles bridge' in response_word:
                response_word = response_word.replace('charles bridge', 'Prague Bridge') # word2vec에 없음
            if 'wii u' in response_word:
                response_word = response_word.replace('wii u', 'wii') # word2vec에 없음
            if 'i will play video ga' in response_word:
                response_word = response_word.replace('i will play video ga', 'play videogame')
            if 'lake lucerne' in response_word:
                response_word = response_word.replace('lake lucerne', 'lake')  # word2vec에 없음
            if 'soul mate' in response_word:
                response_word = response_word.replace('soul mate', 'soulmate') 
            if 'lake louise' in response_word:
                response_word = response_word.replace('lake louise', 'lake') # word2vec에 없음
            if 'jasper national park' in response_word:
                response_word = response_word.replace('jasper national park', 'park') # word2vec에 없음
            if 'in the front my e' in response_word:
                response_word = response_word.replace('in the front my e', '') # word2vec에 없음
            if 'royal ontario museum' in response_word:
                response_word = response_word.replace('royal ontario museum', 'museum') # word2vec에 없음
            if 'kinkaku' in response_word:
                response_word = response_word.replace('kinkaku', '') # word2vec에 없음

            response_words = response_word.split()
            response_words = [word for word in response_words if word not in ['is', 'are', 'for', 'a', 'to', 'the', 'of', 'and', 'in', 'there', 'at', 'this']]

            for i_el in range( len(response_words) ):
                try:
                    vec_word2vec_in = word2vec_model[response_words[i_el]]
                except:
                    except_word = {
                        'Prolific_ID': pilot_data.iloc[i_subject]['Prolific_ID'],
                        'subject': pilot_data.iloc[i_subject]['subject'],
                        'category': column,
                        'word': response_word
                    }
                    except_words.append(except_word)

        # 수정된 단어를 새로운 데이터프레임에 할당
        processed_data.at[i_subject, column] = ' '.join(response_words)

In [154]:
processed_data[0:1]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,friend21,friend22,friend23,friend24,friend25,friend26,friend27,friend28,friend29,friend30
0,5d53bffa147a7d00015aae5a,1,door,gate,outside,grass,itchy,rash,chicken pox,shingles,...,burned down,scary,movies,knocked up,Tinsletown,christmas tree,holiday,decorate,fun,party

In [155]:
except_words

[]

In [156]:
pd.DataFrame(except_words).to_csv(pilot2_dir + '/need_to_be_fixed_again.csv')

In [157]:
processed_data.to_csv(pilot2_dir + '/data/processed/data_after_preprocessing.csv',)