# Word Mover’s Distance(WMD)

NLP연구쪽에서 문서 유사도 구하는 방법으로 잘 쓰인다고 함. (논문 연구 결과 다른 방법론보다 성능이 좋다고 함)\
기본적으로 word2vec을 베이스로 하고, word2vec을 사용해서 word간의 euclide distance를 구함!

- 피험자 1명, seed 단어 1개

피험자가 대답한 30개의 연속적인 단어 그룹 - target word(money, friend, family)의 유사도를 기반으로 wmdistance를 잰다.

--> 그럼 3개의 distance값이 나옴. 그 중 가장 값이 작은 것이 거리가 가깝다. 즉, target word와 유사하다.

wmd 설명 참조
- https://sy-programmingstudy.tistory.com/14
- https://www.youtube.com/watch?v=zFnrq5SmBdg

In [22]:
import os

import pandas as pd
from gensim.models import KeyedVectors

In [23]:
# 현재 프로젝트 폴더 위치 지정. os.getcwd()는 지금 코드 실행하는 현 위치를 출력해줍니다.
pilot2_dir = os.getcwd()
# data/processed 폴더 위치 지정
processed_data_dir = pilot2_dir + '/data/processed/'

In [24]:
# word2vec model 로딩
word2vec_model = KeyedVectors.load_word2vec_format(pilot2_dir + '/../pretrained/GoogleNews-vectors-negative300.bin', binary=True)

In [33]:
# 유사도, 유사도평균 coherence값을 저장한 테이블 읽어오기
pilot_data = pd.read_csv(processed_data_dir + 'similarity_coherence_data_300_with_words.csv', keep_default_na=False)
pilot_data[0:3]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,similarity_friend30_friend,coherence_key_key,coherence_key_money,coherence_key_friend,coherence_money_key,coherence_money_money,coherence_money_friend,coherence_friend_key,coherence_friend_money,coherence_friend_friend
0,5d53bffa147a7d00015aae5a,1,door,gate,outside,grass,itchy,rash,chicken pox,shingles,...,0.19990666,0.041143,0.102066,0.075201,0.030420,0.143791,0.063515,0.037806,0.096950,0.146998
1,5f00ec86304f7322eb8dfa41,2,unlock,door,enter,dreams,time space,possibilites,infinite,time,...,0.17192948,0.096018,0.140075,0.120077,0.053525,0.126333,0.125166,0.081238,0.108360,0.105842
2,5de27ced22383629b807cc70,3,hole,ground,hog,pig,pork,said,dressing,clothes,...,0.058080602,0.079032,0.117155,0.169555,0.057519,0.099424,0.132149,0.049724,0.145488,0.082121

In [26]:
seed_words = ['key', 'money', 'friend'] # 정해진 시드 단어들을 배열에 저장
n_respond_words = 30 # 하나의 시드당 30개의 단어 응답
n_subject = len(pilot_data) # 58명의 피험자

In [38]:
# coherence_wmd_* 컬럼 미리 생성(빈 값)
for seed_word in seed_words:
    for target_word in seed_words:
        column_name = f'distance_{seed_word}_{target_word}'
        pilot_data[column_name] = 0

pilot_data.columns

Index(['Prolific_ID', 'subject', 'key1', 'key2', 'key3', 'key4', 'key5',
       'key6', 'key7', 'key8',
       ...
       'coherence_friend_friend', 'distance_key_key', 'distance_key_money',
       'distance_key_friend', 'distance_money_key', 'distance_money_money',
       'distance_money_friend', 'distance_friend_key', 'distance_friend_money',
       'distance_friend_friend'],
      dtype='object', length=380)

In [39]:
# 응답 단어 컬럼 목록 (예: 'key1', 'key2', ... , 'key30', 'money1', 'money2', ... , 'money30', 'friend1', 'friend2', ... , 'friend30')
word_columns = [f'{seed_word}{i}' for seed_word in seed_words for i in range(1, n_respond_words + 1)]
# word_columns

In [40]:
for i_subject in range(n_subject):
    print('subject: ', i_subject)

    for seed_word in seed_words:
        print('seed: ', seed_word)

        # 각 피험자의 응답 문서를 30개씩 단어 리스트로 변환
        key_response_words = [pilot_data.iloc[i_subject][column] for column in word_columns if column.startswith('key')] # 30개 응답단어
        friend_response_words = [pilot_data.iloc[i_subject][column] for column in word_columns if column.startswith('friend')] # 30개 응답단어
        money_response_words = [pilot_data.iloc[i_subject][column] for column in word_columns if column.startswith('money')] # 30개 응답단어

        try:
            # WMD 거리 계산
            key_wmd_distance = word2vec_model.wmdistance([seed_word], key_response_words) # 응답 30개 단어 - key
            friend_wmd_distance = word2vec_model.wmdistance([seed_word], friend_response_words)  # 응답 30개 단어 - friend
            money_wmd_distance = word2vec_model.wmdistance([seed_word], money_response_words)  # 응답 30개 단어 - money
            # 계산한 WMD를 해당 테이블 위치에 저장
            pilot_data.at[i_subject, f'distance_{seed_word}_key'] = key_wmd_distance
            pilot_data.at[i_subject, f'distance_{seed_word}_friend'] = friend_wmd_distance
            pilot_data.at[i_subject, f'distance_{seed_word}_money'] = money_wmd_distance
            print(f'subject{i_subject}: distance_{seed_word}_key, distance_{seed_word}_friend, distance_{seed_word}_money')
            print(f'key: {key_wmd_distance}, friend: {friend_wmd_distance}, money: {money_wmd_distance}')
        except Exception as e:
            print(f"An error occurred for subject {i_subject}: {str(e)}")
            key_wmd_distance = None
            friend_wmd_distance = None
            money_wmd_distance = None
            continue

subject:  0
seed:  key
subject0: distance_key_key, distance_key_friend, distance_key_money
key: 1.3838922227436379, friend: 1.3863407995830246, money: 1.3919530165556855
seed:  money
subject0: distance_money_key, distance_money_friend, distance_money_money
key: 1.3395049448421927, friend: 1.3434402480968382, money: 1.3048113331692182
seed:  friend
subject0: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.35916976996165, friend: 1.305232927878808, money: 1.3674888038162294
subject:  1
seed:  key
subject1: distance_key_key, distance_key_friend, distance_key_money
key: 1.343760710597814, friend: 1.3549096788266202, money: 1.3752939848744983
seed:  money
subject1: distance_money_key, distance_money_friend, distance_money_money
key: 1.3100134344493806, friend: 1.334133409515669, money: 1.3209716026414686
seed:  friend
subject1: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3249207099597418, friend: 1.3364242897834293, money: 1.3166824524645802
subject:  2
seed:  key
subject2: distance_key_key, distance_key_friend, distance_key_money
key: 1.3556391334083715, friend: 1.3782354830589278, money: 1.3717602774222104
seed:  money
subject2: distance_money_key, distance_money_friend, distance_money_money
key: 1.3278007929715672, friend: 1.2816391013817678, money: 1.340793894307953
seed:  friend
subject2: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2632998748516167, friend: 1.3537801385199655, money: 1.3118234626628031
subject:  3
seed:  key
subject3: distance_key_key, distance_key_friend, distance_key_money
key: 1.3883145219601947, friend: 1.3960057244754318, money: 1.3851198592867124
seed:  money
subject3: distance_money_key, distance_money_friend, distance_money_money
key: 1.3024899618560744, friend: 1.338793451177235, money: 1.3575114676752789
seed:  friend
subject3: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3387241153291283, friend: 1.2905921027657088, money: 1.3380990498321188
subject:  4
seed:  key
subject4: distance_key_key, distance_key_friend, distance_key_money
key: 1.3733177776613998, friend: 1.3620581270105951, money: 1.3745777425579428
seed:  money
subject4: distance_money_key, distance_money_friend, distance_money_money
key: 1.3486476676401233, friend: 1.3487858697376334, money: 1.3039368423457
seed:  friend
subject4: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3582977261223295, friend: 1.3426713585119048, money: 1.343002797906071
subject:  5
seed:  key
subject5: distance_key_key, distance_key_friend, distance_key_money
key: 1.3884983365481811, friend: 1.3635572190562102, money: 1.3896300319283457
seed:  money
subject5: distance_money_key, distance_money_friend, distance_money_money
key: 1.3336836589748873, friend: 1.2631079787525545, money: 1.2951833423747114
seed:  friend
subject5: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3574010365107096, friend: 1.3455393119010604, money: 1.3696432915930665
subject:  6
seed:  key
subject6: distance_key_key, distance_key_friend, distance_key_money
key: 1.3637154303548105, friend: 1.3837809877479745, money: 1.3968877555976162
seed:  money
subject6: distance_money_key, distance_money_friend, distance_money_money
key: 1.3236824491426027, friend: 1.353388824629613, money: 1.3380282519532296
seed:  friend
subject6: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3553791621044333, friend: 1.356749488395004, money: 1.3024377353691878
subject:  7
seed:  key
subject7: distance_key_key, distance_key_friend, distance_key_money
key: 1.3639487546204667, friend: 1.3676088909349036, money: 1.3801412916545306
seed:  money
subject7: distance_money_key, distance_money_friend, distance_money_money
key: 1.3257834344333355, friend: 1.3352002806921608, money: 1.3346685040890143
seed:  friend
subject7: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3096814440189648, friend: 1.2920783947316654, money: 1.3552274060565104
subject:  8
seed:  key

/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3838922227436379' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_key'] = key_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3863407995830246' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_friend'] = friend_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3919530165556855' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_money'] = money_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3395049448421927' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_key'] = key_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3434402480968382' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_friend'] = friend_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3048113331692182' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_money'] = money_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.35916976996165' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_key'] = key_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.305232927878808' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_friend'] = friend_wmd_distance
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_4458/1662622033.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3674888038162294' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'distance_{seed_word}_money'] = money_wmd_distance

subject8: distance_key_key, distance_key_friend, distance_key_money
key: 1.3953941411478121, friend: 1.386092502811169, money: 1.3782332902334526
seed:  money
subject8: distance_money_key, distance_money_friend, distance_money_money
key: 1.3510655025349383, friend: 1.357849855132255, money: 1.3325662161809058
seed:  friend
subject8: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2666198636151735, friend: 1.3341863270010486, money: 1.3399210414348077
subject:  9
seed:  key
subject9: distance_key_key, distance_key_friend, distance_key_money
key: 1.4200233279729184, friend: 1.4108456981650959, money: 1.4069311276493062
seed:  money
subject9: distance_money_key, distance_money_friend, distance_money_money
key: 1.411026499726511, friend: 1.3995249518201511, money: 1.4069904597282419
seed:  friend
subject9: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3702207384236726, friend: 1.370546055471121, money: 1.3694150284038358
subject:  10
seed:  key
subject10: distance_key_key, distance_key_friend, distance_key_money
key: 1.3586366871730569, friend: 1.3969622623074904, money: 1.3869193060360012
seed:  money
subject10: distance_money_key, distance_money_friend, distance_money_money
key: 1.333029179104901, friend: 1.3266505653055842, money: 1.3018831330186933
seed:  friend
subject10: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3634347737752226, friend: 1.222712541352354, money: 1.37427007549772
subject:  11
seed:  key
subject11: distance_key_key, distance_key_friend, distance_key_money
key: 1.352553321349751, friend: 1.3519277801571237, money: 1.3930498039853232
seed:  money
subject11: distance_money_key, distance_money_friend, distance_money_money
key: 1.29561619621747, friend: 1.2547090944854218, money: 1.3541955541206174
seed:  friend
subject11: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3350522613095865, friend: 1.3436106286250464, money: 1.3731840277317582
subject:  12
seed:  key
subject12: distance_key_key, distance_key_friend, distance_key_money
key: 1.3595332111986296, friend: 1.3677984401843224, money: 1.3837255102009538
seed:  money
subject12: distance_money_key, distance_money_friend, distance_money_money
key: 1.353431309858403, friend: 1.354074684273038, money: 1.368891752597366
seed:  friend
subject12: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.34850149249525, friend: 1.3448596250170701, money: 1.352741589890348
subject:  13
seed:  key
subject13: distance_key_key, distance_key_friend, distance_key_money
key: 1.0550169115228727, friend: 1.3224715564212866, money: 1.364837143498567
seed:  money
subject13: distance_money_key, distance_money_friend, distance_money_money
key: 1.347834937130463, friend: 1.3550159118115142, money: 1.266134717902134
seed:  friend
subject13: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3249110045600343, friend: 1.3042280696697888, money: 1.3377890551252358
subject:  14
seed:  key
subject14: distance_key_key, distance_key_friend, distance_key_money
key: 1.381231451802203, friend: 1.3673325494802477, money: 1.3668415468343122
seed:  money
subject14: distance_money_key, distance_money_friend, distance_money_money
key: 1.3472566924789737, friend: 1.328183331842382, money: 1.3299374980531689
seed:  friend
subject14: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3471152489559026, friend: 1.3108490639990251, money: 1.3149582806079667
subject:  15
seed:  key
subject15: distance_key_key, distance_key_friend, distance_key_money
key: 1.3565627786156065, friend: 1.3509237051092209, money: 1.3856430998964622
seed:  money
subject15: distance_money_key, distance_money_friend, distance_money_money
key: 1.3356470903976128, friend: 1.3306994331125896, money: 1.3523075021043798
seed:  friend
subject15: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2873227004096022, friend: 1.3221778619878657, money: 1.3471401793170104
subject:  16
seed:  key
subject16: distance_key_key, distance_key_friend, distance_key_money
key: 1.3933631502443569, friend: 1.400125460839177, money: 1.3593469088890673
seed:  money
subject16: distance_money_key, distance_money_friend, distance_money_money
key: 1.3511658082062894, friend: 1.3240990778412702, money: 1.2906669330646356
seed:  friend
subject16: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3487601001750076, friend: 1.3236554496566388, money: 1.3220882053326872
subject:  17
seed:  key
subject17: distance_key_key, distance_key_friend, distance_key_money
key: 1.414248585313212, friend: 1.4092097381101902, money: 1.4004956831090594
seed:  money
subject17: distance_money_key, distance_money_friend, distance_money_money
key: 1.3870964928042162, friend: 1.3766203520714406, money: 1.4002923473277722
seed:  friend
subject17: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3609885736784268, friend: 1.3842418976799926, money: 1.3772306498272635
subject:  18
seed:  key
subject18: distance_key_key, distance_key_friend, distance_key_money
key: 1.384951704254608, friend: 1.3878694203949102, money: 1.3586029792200558
seed:  money
subject18: distance_money_key, distance_money_friend, distance_money_money
key: 1.3475177911811966, friend: 1.3496618384081676, money: 1.3113362904425028
seed:  friend
subject18: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.292156615224874, friend: 1.2784778800733927, money: 1.3303914830393138
subject:  19
seed:  key
subject19: distance_key_key, distance_key_friend, distance_key_money
key: 1.3386749819003836, friend: 1.3817665595773467, money: 1.3711405129123977
seed:  money
subject19: distance_money_key, distance_money_friend, distance_money_money
key: 1.301236828962646, friend: 1.3349322672744077, money: 1.3389287218770336
seed:  friend
subject19: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.364581936415306, friend: 1.3281914885180528, money: 1.3474619669065468
subject:  20
seed:  key
subject20: distance_key_key, distance_key_friend, distance_key_money
key: 1.3823016987466579, friend: 1.3623523606405836, money: 1.3579828722630773
seed:  money
subject20: distance_money_key, distance_money_friend, distance_money_money
key: 1.3568747608707454, friend: 1.3146278474558963, money: 1.3021677020251137
seed:  friend
subject20: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3495351620535156, friend: 1.310588817213815, money: 1.2964394105593198
subject:  21
seed:  key
subject21: distance_key_key, distance_key_friend, distance_key_money
key: 1.396581874497043, friend: 1.3992830638243605, money: 1.3906351833630664
seed:  money
subject21: distance_money_key, distance_money_friend, distance_money_money
key: 1.3399550150057025, friend: 1.3348566449809411, money: 1.3430026808622897
seed:  friend
subject21: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.308181322104693, friend: 1.3411979717969253, money: 1.346493288226464
subject:  22
seed:  key
subject22: distance_key_key, distance_key_friend, distance_key_money
key: 1.383251351145085, friend: 1.3519963575968448, money: 1.3293508215373364
seed:  money
subject22: distance_money_key, distance_money_friend, distance_money_money
key: 1.340212250787881, friend: 1.2995671612903577, money: 1.2834105383816727
seed:  friend
subject22: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.314140321613365, friend: 1.3054524261724545, money: 1.3463014795764996
subject:  23
seed:  key
subject23: distance_key_key, distance_key_friend, distance_key_money
key: 1.3649230370630838, friend: 1.3604877107430018, money: 1.382700453569519
seed:  money
subject23: distance_money_key, distance_money_friend, distance_money_money
key: 1.3525102088009253, friend: 1.3074984035366848, money: 1.2569344627088537
seed:  friend
subject23: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3283727808096664, friend: 1.2328336358962009, money: 1.3735241766660085
subject:  24
seed:  key
subject24: distance_key_key, distance_key_friend, distance_key_money
key: 1.3808237452584464, friend: 1.3788523070156853, money: 1.3651035353211107
seed:  money
subject24: distance_money_key, distance_money_friend, distance_money_money
key: 1.279244936310606, friend: 1.3408158837541742, money: 1.308722795320118
seed:  friend
subject24: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3267143169399305, friend: 1.3071289101972292, money: 1.3299555745540956
subject:  25
seed:  key
subject25: distance_key_key, distance_key_friend, distance_key_money
key: 1.3626472411064032, friend: 1.305881704167894, money: 1.3568143455274937
seed:  money
subject25: distance_money_key, distance_money_friend, distance_money_money
key: 1.3308895148338997, friend: 1.3216569131188212, money: 1.3141123690150884
seed:  friend
subject25: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3347581951966436, friend: 1.333443190993976, money: 1.339469795607322
subject:  26
seed:  key
subject26: distance_key_key, distance_key_friend, distance_key_money
key: 1.3833413219128619, friend: 1.3961771959619589, money: 1.3902213538656831
seed:  money
subject26: distance_money_key, distance_money_friend, distance_money_money
key: 1.342227485649785, friend: 1.326984474776368, money: 1.3145667481601224
seed:  friend
subject26: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3278421875757709, friend: 1.3296151587685678, money: 1.3383812954420233
subject:  27
seed:  key
subject27: distance_key_key, distance_key_friend, distance_key_money
key: 1.3731906243280825, friend: 1.3440070274388145, money: 1.38690978346556
seed:  money
subject27: distance_money_key, distance_money_friend, distance_money_money
key: 1.347465715904217, friend: 1.3632158285211862, money: 1.329746973782329
seed:  friend
subject27: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3406373607531916, friend: 1.358946437041319, money: 1.3177204663475799
subject:  28
seed:  key
subject28: distance_key_key, distance_key_friend, distance_key_money
key: 1.3209459723871513, friend: 1.3975729225011024, money: 1.3433396290426742
seed:  money
subject28: distance_money_key, distance_money_friend, distance_money_money
key: 1.3284757073904128, friend: 1.287197907198253, money: 1.3034313827346289
seed:  friend
subject28: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3124071791276162, friend: 1.29096604506532, money: 1.3645634942414337
subject:  29
seed:  key
subject29: distance_key_key, distance_key_friend, distance_key_money
key: 1.3893992741608219, friend: 1.380438996526405, money: 1.377497388008602
seed:  money
subject29: distance_money_key, distance_money_friend, distance_money_money
key: 1.3634988353099775, friend: 1.3441963042804919, money: 1.337995417280648
seed:  friend
subject29: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2957469704766782, friend: 1.3084245644221535, money: 1.3277436047407944
subject:  30
seed:  key
subject30: distance_key_key, distance_key_friend, distance_key_money
key: 1.394830940498961, friend: 1.3876527644858794, money: 1.3680447819495496
seed:  money
subject30: distance_money_key, distance_money_friend, distance_money_money
key: 1.363792578581431, friend: 1.3542005479254113, money: 1.3501609408392303
seed:  friend
subject30: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3694338524563738, friend: 1.3202903005006599, money: 1.3744759832777118
subject:  31
seed:  key
subject31: distance_key_key, distance_key_friend, distance_key_money
key: 1.3690606503705565, friend: 1.3357550059565746, money: 1.3392237920726529
seed:  money
subject31: distance_money_key, distance_money_friend, distance_money_money
key: 1.2793138243219349, friend: 1.332425045478032, money: 1.3339586211539292
seed:  friend
subject31: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.341760796316131, friend: 1.269672341012539, money: 1.342161870005958
subject:  32
seed:  key
subject32: distance_key_key, distance_key_friend, distance_key_money
key: 1.3880677354817756, friend: 1.3825516121516648, money: 1.3737922530893392
seed:  money
subject32: distance_money_key, distance_money_friend, distance_money_money
key: 1.2796423915283508, friend: 1.3587712657819628, money: 1.357040457126525
seed:  friend
subject32: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2992768697790826, friend: 1.3330918867766224, money: 1.3293501212338357
subject:  33
seed:  key
subject33: distance_key_key, distance_key_friend, distance_key_money
key: 1.370151293412609, friend: 1.3834362423982014, money: 1.383480203706037
seed:  money
subject33: distance_money_key, distance_money_friend, distance_money_money
key: 1.3462606175717298, friend: 1.3411750262003548, money: 1.3276031506184296
seed:  friend
subject33: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3276843776820029, friend: 1.2834842753401041, money: 1.35264436759662
subject:  34
seed:  key
subject34: distance_key_key, distance_key_friend, distance_key_money
key: 1.3414939721966992, friend: 1.3300614717556658, money: 1.3600700980743798
seed:  money
subject34: distance_money_key, distance_money_friend, distance_money_money
key: 1.3417701590705668, friend: 1.338565435581987, money: 1.2963889242331457
seed:  friend
subject34: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2765339366254165, friend: 1.3303455139060858, money: 1.3779882014919502
subject:  35
seed:  key
subject35: distance_key_key, distance_key_friend, distance_key_money
key: 1.3530004454282958, friend: 1.350414165434249, money: 1.3521957871723531
seed:  money
subject35: distance_money_key, distance_money_friend, distance_money_money
key: 1.3048850555469451, friend: 1.308583163581861, money: 1.304828452830061
seed:  friend
subject35: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.31659656572408, friend: 1.2945981762029373, money: 1.3534182060249318
subject:  36
seed:  key
subject36: distance_key_key, distance_key_friend, distance_key_money
key: 1.3733624748973847, friend: 1.3555813274015924, money: 1.3709719377181664
seed:  money
subject36: distance_money_key, distance_money_friend, distance_money_money
key: 1.3366079940298514, friend: 1.3250602606143516, money: 1.3444896128134887
seed:  friend
subject36: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2653869074079456, friend: 1.3152569843745123, money: 1.3565478497981345
subject:  37
seed:  key
subject37: distance_key_key, distance_key_friend, distance_key_money
key: 1.3735281563184834, friend: 1.3867324749073675, money: 1.3891167304258452
seed:  money
subject37: distance_money_key, distance_money_friend, distance_money_money
key: 1.2791539799885427, friend: 1.3602283464413387, money: 1.3368292188447772
seed:  friend
subject37: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3534431517536387, friend: 1.345239228564299, money: 1.3382173132759623
subject:  38
seed:  key
subject38: distance_key_key, distance_key_friend, distance_key_money
key: 1.3699648484728726, friend: 1.3611638999341407, money: 1.3804250735678212
seed:  money
subject38: distance_money_key, distance_money_friend, distance_money_money
key: 1.3386398940847852, friend: 1.3505273155986721, money: 1.3211903625577124
seed:  friend
subject38: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3517363286188275, friend: 1.3481859632585245, money: 1.3713532076132462
subject:  39
seed:  key
subject39: distance_key_key, distance_key_friend, distance_key_money
key: 1.3355881069192115, friend: 1.3719482171991764, money: 1.3795147169588033
seed:  money
subject39: distance_money_key, distance_money_friend, distance_money_money
key: 1.3445650001105451, friend: 1.3284045909558309, money: 1.3205810446524606
seed:  friend
subject39: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3358691213629612, friend: 1.2954500845783938, money: 1.3378376924135185
subject:  40
seed:  key
subject40: distance_key_key, distance_key_friend, distance_key_money
key: 1.375402986483348, friend: 1.3944526003661746, money: 1.3964895838257365
seed:  money
subject40: distance_money_key, distance_money_friend, distance_money_money
key: 1.2552444484580894, friend: 1.3365335265606304, money: 1.3167240802677962
seed:  friend
subject40: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.2984238275829563, friend: 1.3061401566393493, money: 1.2963726175889911
subject:  41
seed:  key
subject41: distance_key_key, distance_key_friend, distance_key_money
key: 1.3942031707084466, friend: 1.3781515697423863, money: 1.3825093823709298
seed:  money
subject41: distance_money_key, distance_money_friend, distance_money_money
key: 1.3516401341908566, friend: 1.339662785353067, money: 1.3346963745041749
seed:  friend
subject41: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3185605498126964, friend: 1.3004355509307781, money: 1.3152531412826092
subject:  42
seed:  key
subject42: distance_key_key, distance_key_friend, distance_key_money
key: 1.363823443954431, friend: 1.3566377063859922, money: 1.3897821271953128
seed:  money
subject42: distance_money_key, distance_money_friend, distance_money_money
key: 1.3296425090072927, friend: 1.2876415632531923, money: 1.3162772781222498
seed:  friend
subject42: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3166585736681027, friend: 1.3063760987435888, money: 1.3097105281523227
subject:  43
seed:  key
subject43: distance_key_key, distance_key_friend, distance_key_money
key: 1.3809971853236498, friend: 1.3567636410139972, money: 1.3690571849303979
seed:  money
subject43: distance_money_key, distance_money_friend, distance_money_money
key: 1.2833463887124739, friend: 1.3142030558822988, money: 1.311166062569934
seed:  friend
subject43: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3638481550625787, friend: 1.3138660899624737, money: 1.3028767207377876
subject:  44
seed:  key
subject44: distance_key_key, distance_key_friend, distance_key_money
key: 1.349552176632572, friend: 1.388537023822222, money: 1.3746768218047871
seed:  money
subject44: distance_money_key, distance_money_friend, distance_money_money
key: 1.3426531320836703, friend: 1.3379309531935426, money: 1.3312577627999371
seed:  friend
subject44: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.35612398207629, friend: 1.3348034432401954, money: 1.330081226063827
subject:  45
seed:  key
subject45: distance_key_key, distance_key_friend, distance_key_money
key: 1.3860775347604668, friend: 1.398896464321906, money: 1.3809253237187817
seed:  money
subject45: distance_money_key, distance_money_friend, distance_money_money
key: 1.3688705424508936, friend: 1.3742231100309394, money: 1.32760712168243
seed:  friend
subject45: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.345958724711843, friend: 1.3450800017398195, money: 1.33103557884195
subject:  46
seed:  key
subject46: distance_key_key, distance_key_friend, distance_key_money
key: 1.3615619415946159, friend: 1.3703887402534356, money: 1.3573614418822981
seed:  money
subject46: distance_money_key, distance_money_friend, distance_money_money
key: 1.3252070020448687, friend: 1.3517437881201666, money: 1.3384199632464904
seed:  friend
subject46: distance_friend_key, distance_friend_friend, distance_friend_money
key: 1.3501910453226933, friend: 1.3443753900180728, money: 1.3589872969326844
subject:  47
seed:  key
subject47: distance_key_key, distance_key_friend, distance_key_money
key: 1.3891936815273476, friend: 1.3575482321244938, money: 1.4009737278065748
seed:  money

In [41]:
pilot_data[0:3]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,coherence_friend_friend,distance_key_key,distance_key_money,distance_key_friend,distance_money_key,distance_money_money,distance_money_friend,distance_friend_key,distance_friend_money,distance_friend_friend
0,5d53bffa147a7d00015aae5a,1,door,gate,outside,grass,itchy,rash,chicken pox,shingles,...,0.146998,1.383892,1.391953,1.386341,1.339505,1.304811,1.343440,1.359170,1.367489,1.305233
1,5f00ec86304f7322eb8dfa41,2,unlock,door,enter,dreams,time space,possibilites,infinite,time,...,0.105842,1.343761,1.375294,1.354910,1.310013,1.320972,1.334133,1.324921,1.316682,1.336424
2,5de27ced22383629b807cc70,3,hole,ground,hog,pig,pork,said,dressing,clothes,...,0.082121,1.355639,1.371760,1.378235,1.327801,1.340794,1.281639,1.263300,1.311823,1.353780

In [10]:
# # 단어 있는 버전 csv 저장
# pilot_data.to_csv(processed_data_dir + 'similarity_coherence_data_300_with_words_2.csv', index=None)

# # 단어 컬럼들 드롭
# drop_columns = pilot_data.columns[1:91]
# pilot_data = pilot_data.drop(drop_columns, axis='columns')

# # 단어 없이 coherence만 있는 버전 csv 저장
# pilot_data.to_csv(processed_data_dir + 'similarity_coherence_data_300_2.csv', index=None)