# Word Mover’s Distance(WMD)

NLP연구쪽에서 문서 유사도 구하는 방법으로 잘 쓰인다고 함. (논문 연구 결과 다른 방법론보다 성능이 좋다고 함)\
기본적으로 word2vec을 베이스로 하고, word2vec을 사용해서 word간의 euclide distance를 구함!

- 피험자 1명, seed 단어 1개

피험자가 대답한 30개의 연속적인 단어 그룹 - target word(money, friend, family)의 유사도를 기반으로 wmdistance를 잰다.

--> 그럼 3개의 distance값이 나옴. 그 중 가장 값이 작은 것이 거리가 가깝다. 즉, target word와 유사하다.

wmd 설명 참조
- https://sy-programmingstudy.tistory.com/14
- https://www.youtube.com/watch?v=zFnrq5SmBdg

In [1]:
import os
import platform

import pandas as pd
import numpy as np
from gensim.models import KeyedVectors

In [2]:
os_system = platform.system() # 맥북은 Darwin, 윈도우는 Windows

# 현재 프로젝트 폴더 위치 지정. os.getcwd()는 지금 코드 실행하는 현 위치를 출력해줍니다.
pilot2_dir = os.getcwd()
model_path = '\\..\\pretrained\\GoogleNews-vectors-negative300.bin' if os_system == 'Windows' else '/../pretrained/GoogleNews-vectors-negative300.bin'

# data/processed 폴더 위치 지정
processed_data_dir = pilot2_dir + ('\\data\\processed\\' if os_system == 'Windows' else '/data/processed/')

In [3]:
# word2vec model 로딩
word2vec_model = KeyedVectors.load_word2vec_format(pilot2_dir + model_path, binary=True)

In [4]:
# 테이블 읽어오기
pilot_data = pd.read_csv(processed_data_dir + 'merged_data.csv', keep_default_na=False)
pilot_data[0:3]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,friend21,friend22,friend23,friend24,friend25,friend26,friend27,friend28,friend29,friend30
0,5d53bffa147a7d00015aae5a,1,Door,Gate,Outside,Grass,Itchy,Rash,Chicken pox,Shingles,...,Burned down,Scary,Movies,Knocked up,Tinsletown,Christmas tree,Holiday,Decorate,Fun,Party
1,5f00ec86304f7322eb8dfa41,2,Unlock,Door,Enter,Dreams,Time and space,Possibilites,Infinite,Time,...,Transparent,Glass,Shattered,Repair,Meaningful,Bond,Glue,All together,Matters,Wonders
2,5de27ced22383629b807cc70,3,Hole,Ground,Hog,Pig,Pork,Sald,Dressing,Clothes,...,Sunshine,Wamrth,Blanket,Heavy,Body,Muscle,Protein,Shake,Dance,Jump

In [5]:
seed_words = ['key', 'money', 'friend'] # 정해진 시드 단어들을 배열에 저장
target_words = ['key', 'money', 'friend'] # seed_words와 동일
n_respond_words = 30 # 하나의 시드당 30개의 단어 응답
n_subject = len(pilot_data) # 58명의 피험자

In [6]:
# wmd_seed_target 컬럼 미리 생성(빈 값)
for target_word in seed_words:
    for seed_word in seed_words:
        column_name = f'wmd_{seed_word}_{target_word}'
        pilot_data[column_name] = 0

    column_name = f'wmd_{target_word}'
    pilot_data[column_name] = np.nan

pilot_data.columns

Index(['Prolific_ID', 'subject', 'key1', 'key2', 'key3', 'key4', 'key5',
       'key6', 'key7', 'key8',
       ...
       'wmd_friend_key', 'wmd_key', 'wmd_key_money', 'wmd_money_money',
       'wmd_friend_money', 'wmd_money', 'wmd_key_friend', 'wmd_money_friend',
       'wmd_friend_friend', 'wmd_friend'],
      dtype='object', length=104)

In [7]:
# 응답 단어 컬럼 목록 (예: 'key1', 'key2', ... , 'key30', 'money1', 'money2', ... , 'money30', 'friend1', 'friend2', ... , 'friend30')
word_columns = [f'{seed_word}{i}' for seed_word in seed_words for i in range(1, n_respond_words + 1)]
# word_columns

In [8]:
for i_subject in range(n_subject):
    # print('subject: ', i_subject)

    for target_word in target_words: # key, money, friend
        for seed_word in seed_words: # key, money, friend
            # 각 피험자의 응답 문서를 30개씩 단어 리스트로 반환
            seed_response_words = [pilot_data.iloc[i_subject][column] for column in word_columns if column.startswith(seed_word)]
            # nan값 걸러내기
            seed_response_words = [word for word in seed_response_words if not isinstance(word, float) or not np.isnan(word)] 

            if len(seed_response_words) > 0: # 애초에 값이 0인 피험자 데이터들은 건너뛰도록 함
                try:
                    # 응답 30개 단어 - target 단어의 WMD 계산
                    wmdistance_value = word2vec_model.wmdistance([target_word], seed_response_words)

                    # 계산한 WMD를 해당 테이블 위치에 저장
                    pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
                    print(f'wmd_{seed_word}_{target_word}: {wmdistance_value}')
                except Exception as e:
                    print(f"An error occurred for subject {i_subject}: {str(e)}")
                    continue

        # 각 피험자의 응답 단어 90개 모두를 리스트로 반환
        total_response_words = [pilot_data.iloc[i_subject][column] for column in word_columns]
        # 응답 90개 단어 - target 단어의 WMD 계산
        total_wmdistance_value = word2vec_model.wmdistance([target_word], total_response_words)

        # 계산한 WMD를 해당 테이블 위치에 저장
        pilot_data.at[i_subject, f'wmd_{target_word}'] = total_wmdistance_value
        print(f'wmd_{target_word}: {total_wmdistance_value}')

/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3910585478548874' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3942253176490893' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3915910726066376' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3845510880725866' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3491492930807292' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.383315853364714' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3851616851166642' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3744623151847684' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value
/var/folders/99/w9lwt31s6gzbvts3vs5x6myr0000gn/T/ipykernel_24945/1147595627.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.3459576823925368' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pilot_data.at[i_subject, f'wmd_{seed_word}_{target_word}'] = wmdistance_value

wmd_key_key: 1.3910585478548874
wmd_money_key: 1.3942253176490893
wmd_friend_key: 1.3915910726066376
wmd_key: 1.3923828126406326
wmd_key_money: 1.3845510880725866
wmd_money_money: 1.3491492930807292
wmd_friend_money: 1.383315853364714
wmd_money: 1.3711802312655899
wmd_key_friend: 1.3851616851166642
wmd_money_friend: 1.3744623151847684
wmd_friend_friend: 1.3459576823925368
wmd_friend: 1.369323991529271
wmd_key_key: 1.3633910786884351
wmd_money_key: 1.3708503212617251
wmd_friend_key: 1.364012203913959
wmd_key: 1.3662171178677116
wmd_key_money: 1.3726648953986884
wmd_money_money: 1.3770626622949786
wmd_friend_money: 1.3831599049968222
wmd_money: 1.378247524967348
wmd_key_friend: 1.3643633157840414
wmd_money_friend: 1.365838365079093
wmd_friend_friend: 1.3776102556984484
wmd_friend: 1.3699968163065634
wmd_key_key: 1.3857931180890057
wmd_money_key: 1.3809168682137871
wmd_friend_key: 1.369404984650579
wmd_key: 1.378907312952833
wmd_key_money: 1.375483996226461
wmd_money_money: 1.3866505154693503
wmd_friend_money: 1.3558977447135097
wmd_money: 1.3729192243773412
wmd_key_friend: 1.3571666076219306
wmd_money_friend: 1.3620127795558525
wmd_friend_friend: 1.3945519689063381
wmd_friend: 1.3707822376911956
wmd_key_key: 1.3962635264861627
wmd_money_key: 1.3913293401105284
wmd_friend_key: 1.3901471750563867
wmd_key: 1.3925800138843598
wmd_key_money: 1.3685383278172107
wmd_money_money: 1.3804296441108748
wmd_friend_money: 1.3722702815391614
wmd_money: 1.3737460844890825
wmd_key_friend: 1.3850619271890345
wmd_money_friend: 1.3745457825556269
wmd_friend_friend: 1.3574449542143774
wmd_friend: 1.372350887986347
wmd_key_key: 1.3847451821672336
wmd_money_key: 1.3756918687746906
wmd_friend_key: 1.3756253614803853
wmd_key: 1.3786874708074364
wmd_key_money: 1.3942088271709911
wmd_money_money: 1.3637822134836262
wmd_friend_money: 1.3895009937327563
wmd_money: 1.3824973447957911
wmd_key_friend: 1.393605761307747
wmd_money_friend: 1.3963924361072626
wmd_friend_friend: 1.385760960300723
wmd_friend: 1.3919197192385773
wmd_key_key: 1.4016439865939565
wmd_money_key: 1.393584302358213
wmd_friend_key: 1.369902246947195
wmd_key: 1.388685383469418
wmd_key_money: 1.3749202307453687
wmd_money_money: 1.3526492543831532
wmd_friend_money: 1.3537971616499143
wmd_money: 1.3607919368754282
wmd_key_friend: 1.3948586411292379
wmd_money_friend: 1.388917815997147
wmd_friend_friend: 1.3882624432370136
wmd_friend: 1.390776819679459
wmd_key_key: 1.3778717742387272
wmd_money_key: 1.397431912763707
wmd_friend_key: 1.3836890584440262
wmd_key: 1.38633091514882
wmd_key_money: 1.3678584698574496
wmd_money_money: 1.3779934807763587
wmd_friend_money: 1.3938894476652117
wmd_money: 1.3799137994330075
wmd_key_friend: 1.3671164317414692
wmd_money_friend: 1.340959106377183
wmd_friend_friend: 1.3722378637898254
wmd_friend: 1.3601044673028257
wmd_key_key: 1.379498260442269
wmd_money_key: 1.3820884099892659
wmd_friend_key: 1.374634003893097
wmd_key: 1.3787863620881535
wmd_key_money: 1.381997351378192
wmd_money_money: 1.3827044501674601
wmd_friend_money: 1.3802628313831273
wmd_money: 1.381670518612135
wmd_key_friend: 1.377736572061021
wmd_money_friend: 1.4041361532525283
wmd_friend_friend: 1.3512201818394953
wmd_friend: 1.3779951351994568
wmd_key_key: 1.3997301320744688
wmd_money_key: 1.3840060282851134
wmd_friend_key: 1.3983400190487256
wmd_key: 1.393895739978413
wmd_key_money: 1.372015968176754
wmd_money_money: 1.3777106760873257
wmd_friend_money: 1.3933282557214726
wmd_money: 1.381222898445603
wmd_key_friend: 1.3588869815294646
wmd_money_friend: 1.371591180394829
wmd_friend_friend: 1.3828633965893005
wmd_friend: 1.371391736276692
wmd_key_key: 1.3968040614619868
wmd_money_key: 1.3870761427416352
wmd_friend_key: 1.398858286797973
wmd_key: 1.3954289068310133
wmd_key_money: 1.3801495488410176
wmd_money_money: 1.3921577289113334
wmd_friend_money: 1.4095846364705984
wmd_money: 1.391769027085436
wmd_key_friend: 1.3862515689237478
wmd_money_friend: 1.3976852444449661
wmd_friend_friend: 1.39667978483792
wmd_friend: 1.3918534998325363
wmd_key_key: 1.3744817227026829
wmd_money_key: 1.38730514689776
wmd_friend_key: 1.3999502190846134
wmd_key: 1.3872450049414964
wmd_key_money: 1.384867457925264
wmd_money_money: 1.3570969137974978
wmd_friend_money: 1.367808460711122
wmd_money: 1.370073432869593
wmd_key_friend: 1.395691436549605
wmd_money_friend: 1.3881964075315656
wmd_friend_friend: 1.3233586490386102
wmd_friend: 1.3688599057318829
wmd_key_key: 1.3909603755742737
wmd_money_key: 1.3895585828610695
wmd_friend_key: 1.3738902366236618
wmd_key: 1.3828232304147063
wmd_key_money: 1.3817464083804503
wmd_money_money: 1.3904062947903528
wmd_friend_money: 1.3273786471209812
wmd_money: 1.3600953788969072
wmd_key_friend: 1.3729207161108905
wmd_money_friend: 1.3681092828756418
wmd_friend_friend: 1.3678622146078998
wmd_friend: 1.3690806746330888
wmd_key_key: 1.3810174307797782
wmd_money_key: 1.392376345315494
wmd_friend_key: 1.38567817649278
wmd_key: 1.3863573175293502
wmd_key_money: 1.3813161663825024
wmd_money_money: 1.3982135869323242
wmd_friend_money: 1.39198259501225
wmd_money: 1.3905041161090252
wmd_key_friend: 1.3809575659486601
wmd_money_friend: 1.369013084041929
wmd_friend_friend: 1.3768845111058539
wmd_friend: 1.3756183870321483
wmd_key_key: 1.312739443070781
wmd_money_key: 1.3648496407217845
wmd_friend_key: 1.3807316684847941
wmd_key: 1.3518089059955447
wmd_key_money: 1.369316588835427
wmd_money_money: 1.365321176627247
wmd_friend_money: 1.3883621431003954
wmd_money: 1.3742124181792004
wmd_key_friend: 1.3701483713587894
wmd_money_friend: 1.3901737442464843
wmd_friend_friend: 1.3742154458599232
wmd_friend: 1.377985673521419
wmd_key_key: 1.3821394425009248
wmd_money_key: 1.371755621953345
wmd_friend_key: 1.3762636427979362
wmd_key: 1.3767246918513254
wmd_key_money: 1.3919365704616495
wmd_money_money: 1.3737623946780944
wmd_friend_money: 1.3802283662654364
wmd_money: 1.3819954109650536
wmd_key_friend: 1.38818132640569
wmd_money_friend: 1.359021126315536
wmd_friend_friend: 1.3710673181596875
wmd_friend: 1.37277557087941
wmd_key_key: 1.368745478513792
wmd_money_key: 1.3930388429247926
wmd_friend_key: 1.3695292115628992
wmd_key: 1.3771896267245105
wmd_key_money: 1.3873488135314074
wmd_money_money: 1.38609627424628
wmd_friend_money: 1.3791910625904606
wmd_money: 1.3842684657129636
wmd_key_friend: 1.3649897852505117
wmd_money_friend: 1.373496920738267
wmd_friend_friend: 1.377427916585201
wmd_friend: 1.3719102332655506
wmd_key_key: 1.3889245546209943
wmd_money_key: 1.3759033391361495
wmd_friend_key: 1.4038160366716852
wmd_key: 1.3930819600880715
wmd_key_money: 1.3940264699585012
wmd_money_money: 1.346126915892497
wmd_friend_money: 1.376641960591292
wmd_money: 1.377433397621175
wmd_key_friend: 1.3638401201704944
wmd_money_friend: 1.3582994015457108
wmd_friend_friend: 1.3915930322690935
wmd_friend: 1.3750722034466594
wmd_key_key: 1.4163499917772466
wmd_money_key: 1.4167850032274525
wmd_friend_key: inf
wmd_key: 1.4164224936856142
wmd_key_money: 1.361031071244415
wmd_money_money: 1.4200276009989734
wmd_friend_money: inf
wmd_money: 1.3708638262035078
wmd_key_friend: 1.3763680982370075
wmd_money_friend: 1.3764741530254527
wmd_friend_friend: inf
wmd_friend: 1.3763857740350816
wmd_key_key: 1.3958190026201203
wmd_money_key: 1.3923926771610964
wmd_friend_key: 1.3934364311644887
wmd_key: 1.393860188544247
wmd_key_money: 1.3776897025679213
wmd_money_money: 1.377484657622155
wmd_friend_money: 1.37382212353904
wmd_money: 1.3763163758787937
wmd_key_friend: 1.3649706330277094
wmd_money_friend: 1.375675181023229
wmd_friend_friend: 1.3545807361901079
wmd_friend: 1.3650767363251455
wmd_key_key: 1.3610844363745074
wmd_money_key: 1.37803159444639
wmd_friend_key: 1.3824375972160798
wmd_key: 1.373851209345659
wmd_key_money: 1.3640962892108017
wmd_money_money: 1.381835248137987
wmd_friend_money: 1.37420485095056
wmd_money: 1.3733787960997832
wmd_key_friend: 1.389178550942652
wmd_money_friend: 1.3900115990790738
wmd_friend_friend: 1.3751823988800786
wmd_friend: 1.3847908496339345
wmd_key_key: 1.3846920925994748
wmd_money_key: 1.3776391062601103
wmd_friend_key: 1.3704765204086742
wmd_key: 1.3776025730894192
wmd_key_money: 1.3861147742040139
wmd_money_money: 1.359197618216029
wmd_friend_money: 1.3818124395359885
wmd_money: 1.3757082773186775
wmd_key_friend: 1.3853874526344856
wmd_money_friend: 1.3475891408562273
wmd_friend_friend: 1.3726102278103909
wmd_friend: 1.368528940433701
wmd_key_key: 1.3949434905570466
wmd_money_key: 1.4016924695413715
wmd_friend_key: 1.393647662815455
wmd_key: 1.3968025193897966
wmd_key_money: 1.3875950122180267
wmd_money_money: 1.3846961608771102
wmd_friend_money: 1.3775924829664847
wmd_money: 1.3831968142887798
wmd_key_friend: 1.3740991387579258
wmd_money_friend: 1.3813287998343178
wmd_friend_friend: 1.3733070684143207
wmd_friend: 1.3762937719622845
wmd_key_key: 1.3917279184390314
wmd_money_key: 1.3625169324985145
wmd_friend_key: 1.3755687595342156
wmd_key: 1.3765152847314919
wmd_key_money: 1.3874868989364706
wmd_money_money: 1.3471784218877412
wmd_friend_money: 1.3600109873316524
wmd_money: 1.365220337215002
wmd_key_friend: 1.3765335550827786
wmd_money_friend: 1.3566381375284724
wmd_friend_friend: 1.3457539901535256
wmd_friend: 1.3613049631177656
wmd_key_key: 1.3746848154701516
wmd_money_key: 1.3882407422162106
wmd_friend_key: 1.3721983342183894
wmd_key: 1.3785462499449048
wmd_key_money: 1.3856080416644925
wmd_money_money: 1.339338591701174
wmd_friend_money: 1.358886191192377
wmd_money: 1.3601459601172459
wmd_key_friend: 1.3690597529756487
wmd_money_friend: 1.378919928588769
wmd_friend_friend: 1.336966610831368
wmd_friend: 1.361304066976405
wmd_key_key: 1.3843337232162711
wmd_money_key: 1.3791957005607505
wmd_friend_key: 1.387103353394841
wmd_key: 1.383544259057288
wmd_key_money: 1.36925117758462
wmd_money_money: 1.3718451089287804
wmd_friend_money: 1.3847085199098368
wmd_money: 1.3752682688077456
wmd_key_friend: 1.3708890831077314
wmd_money_friend: 1.3739773449343926
wmd_friend_friend: 1.3692912144958775
wmd_friend: 1.3713858808460009
wmd_key_key: 1.3707483719883378
wmd_money_key: 1.3740824494787487
wmd_friend_key: 1.3525181126359198
wmd_key: 1.3658394029656304
wmd_key_money: 1.3708748487314824
wmd_money_money: 1.3686574416503479
wmd_friend_money: 1.3716052868007322
wmd_money: 1.3703848248525654
wmd_key_friend: 1.3612601602154981
wmd_money_friend: 1.3765420295025244
wmd_friend_friend: 1.3799002221903862
wmd_friend: 1.3724389784722653
wmd_key_key: 1.383161240579813
wmd_money_key: 1.389067041622046
wmd_friend_key: 1.3941020443128356
wmd_key: 1.3886465278414097
wmd_key_money: 1.3837404013657366
wmd_money_money: 1.3735393176096569
wmd_friend_money: 1.3762247555510165
wmd_money: 1.3779242968161218
wmd_key_friend: 1.376803836866395
wmd_money_friend: 1.3876126066127739
wmd_friend_friend: 1.3772632353031369
wmd_friend: 1.3805544238984264
wmd_key_key: 1.3806615926795887
wmd_money_key: 1.3836742142392435
wmd_friend_key: 1.3787017021224823
wmd_key: 1.3805288856630933
wmd_key_money: 1.4022909606836367
wmd_money_money: 1.3714859128173773
wmd_friend_money: 1.4006259631951454
wmd_money: 1.395322527153888
wmd_key_friend: 1.3718175200557365
wmd_money_friend: 1.3580010974063639
wmd_friend_friend: 1.389122557717538
wmd_friend: 1.3756160777925832
wmd_key_key: 1.36217639233713
wmd_money_key: 1.3617030603959175
wmd_friend_key: 1.38908394480916
wmd_key: 1.3707697733297897
wmd_key_money: 1.375365641600403
wmd_money_money: 1.3661174362880049
wmd_friend_money: 1.3559248231629293
wmd_money: 1.3659216434490895
wmd_key_friend: 1.3725663733883375
wmd_money_friend: 1.402450385847172
wmd_friend_friend: 1.357907141509726
wmd_friend: 1.3778790611970688
wmd_key_key: 1.4025466837871885
wmd_money_key: 1.3906362069307743
wmd_friend_key: 1.389774193199375
wmd_key: 1.394319027972446
wmd_key_money: 1.3908620281744808
wmd_money_money: 1.3777151807678147
wmd_friend_money: 1.3863223831951992
wmd_money: 1.3849665307124979
wmd_key_friend: 1.3536583045755075
wmd_money_friend: 1.3622754483014
wmd_friend_friend: 1.3635468228823007
wmd_friend: 1.3598268585864026
wmd_key_key: 1.3916221474437855
wmd_money_key: 1.3583960765982992
wmd_friend_key: 1.3861498776142398
wmd_key: 1.3787227005521085
wmd_key_money: 1.391550434399186
wmd_money_money: 1.3983606146379766
wmd_friend_money: 1.398109527558946
wmd_money: 1.3960068588653696
wmd_key_friend: 1.392170768586102
wmd_money_friend: 1.4046973302214203
wmd_friend_friend: 1.3761695681855735
wmd_friend: 1.391012555664365
wmd_key_key: 1.3857299204301363
wmd_money_key: 1.3839746360754668
wmd_friend_key: 1.3535691395536715
wmd_key: 1.3743051894690628
wmd_key_money: 1.363712819683428
wmd_money_money: 1.3835559496147989
wmd_friend_money: 1.3746083206669482
wmd_money: 1.3738390684930628
wmd_key_friend: 1.383911407721551
wmd_money_friend: 1.3763815712684577
wmd_friend_friend: 1.3538495774656754
wmd_friend: 1.3713183431629388
wmd_key_key: 1.389593818034478
wmd_money_key: 1.3917958089675593
wmd_friend_key: 1.3869657059379923
wmd_key: 1.389419566571276
wmd_key_money: 1.3517121606891138
wmd_money_money: 1.3852595506556251
wmd_friend_money: 1.385004793008351
wmd_money: 1.374638361603135
wmd_key_friend: 1.381865279869587
wmd_money_friend: 1.3764324921331537
wmd_friend_friend: 1.3800766637267432
wmd_friend: 1.3794093574435171
wmd_key_key: 1.367083566983095
wmd_money_key: 1.3851339184724882
wmd_friend_key: 1.3921432384190093
wmd_key: 1.3814107799289603
wmd_key_money: 1.3891899477356293
wmd_money_money: 1.3780508172130579
wmd_friend_money: 1.382560118809301
wmd_money: 1.3833276140903308
wmd_key_friend: 1.3790969847773928
wmd_money_friend: 1.389710934122271
wmd_friend_friend: 1.358991864709135
wmd_friend: 1.3757730557038699
wmd_key_key: 1.3632663864442685
wmd_money_key: 1.3618969049048242
wmd_friend_key: 1.368687617875583
wmd_key: 1.3646169697415582
wmd_key_money: 1.3865975981773027
wmd_money_money: 1.3634878706029863
wmd_friend_money: 1.3764428460559912
wmd_money: 1.37550943827876
wmd_key_friend: 1.358720399880762
wmd_money_friend: 1.3852143955002458
wmd_friend_friend: 1.3761804622246205
wmd_friend: 1.3733717525352096
wmd_key_key: 1.359291581108216
wmd_money_key: 1.3645717342828854
wmd_friend_key: 1.3646229406224133
wmd_key: 1.3628287520045048
wmd_key_money: 1.3654652738399216
wmd_money_money: 1.3722170534264349
wmd_friend_money: 1.3592004943288558
wmd_money: 1.3656276071984041
wmd_key_friend: 1.3588499318569098
wmd_money_friend: 1.3932394813352378
wmd_friend_friend: 1.3582725886592781
wmd_friend: 1.3701206672838087
wmd_key_key: 1.3898452429683406
wmd_money_key: 1.3776143494104796
wmd_friend_key: 1.3699820040032167
wmd_key: 1.379164421820791
wmd_key_money: 1.379440732238151
wmd_money_money: 1.3850048907119101
wmd_friend_money: 1.3749802573897612
wmd_money: 1.379750241791939
wmd_key_friend: 1.3521458657068468
wmd_money_friend: 1.3860660250385672
wmd_friend_friend: 1.373577648160099
wmd_friend: 1.3704226982261418
wmd_key_key: 1.3785758333771554
wmd_money_key: 1.3907295799181005
wmd_friend_key: 1.3882593311873603
wmd_key: 1.3858557079886324
wmd_key_money: 1.3639849133289461
wmd_money_money: 1.387903962089563
wmd_friend_money: 1.385336084195544
wmd_money: 1.3790304899143597
wmd_key_friend: 1.3913354132390354
wmd_money_friend: 1.3804796161412964
wmd_friend_friend: 1.37545212492714
wmd_friend: 1.3825669359866992
wmd_key_key: 1.3800973043699216
wmd_money_key: 1.3944308623245116
wmd_friend_key: 1.376667013389289
wmd_key: 1.3838143272019525
wmd_key_money: 1.385446896691556
wmd_money_money: 1.3672715753063978
wmd_friend_money: 1.4032822996372412
wmd_money: 1.3853310154053717
wmd_key_friend: 1.3832330852129366
wmd_money_friend: 1.3822818897232192
wmd_friend_friend: 1.3748131502906331
wmd_friend: 1.3800383816633834
wmd_key_key: 1.3502776665442706
wmd_money_key: 1.3699207759337972
wmd_friend_key: 1.400928018229075
wmd_key: 1.3783950509740022
wmd_key_money: 1.4111161912718677
wmd_money_money: 1.3754821610358858
wmd_friend_money: 1.3773827784380448
wmd_money: 1.383369214043946
wmd_key_friend: 1.4016853720561213
wmd_money_friend: 1.3634162598772017
wmd_friend_friend: 1.3539571980345033
wmd_friend: 1.3672864575759065
wmd_key_key: 1.3864677604665896
wmd_money_key: 1.390370914672041
wmd_friend_key: 1.3986090439913041
wmd_key: 1.3917392640066892
wmd_key_money: 1.3498554399771627
wmd_money_money: 1.3698009290554398
wmd_friend_money: 1.3748451668014623
wmd_money: 1.3642933867005032
wmd_key_friend: 1.3721080449492564
wmd_money_friend: 1.3778559310455976
wmd_friend_friend: 1.365574037173814
wmd_friend: 1.3716350923552332
wmd_key_key: 1.3946463158996683
wmd_money_key: 1.3917256416691721
wmd_friend_key: 1.3875993713256467
wmd_key: 1.3913285041260568
wmd_key_money: 1.3856742746892898
wmd_money_money: 1.3844447309704702
wmd_friend_money: 1.3784898728844668
wmd_money: 1.3828881568259868
wmd_key_friend: 1.3730272867274824
wmd_money_friend: 1.3680190566851493
wmd_friend_friend: 1.3596823169856753
wmd_friend: 1.3669226064451494
wmd_key_key: 1.3910665618853582
wmd_money_key: 1.3930510320614515
wmd_friend_key: 1.3765054411954352
wmd_key: 1.3868025231053895
wmd_key_money: 1.3822299660450508
wmd_money_money: 1.3711733224419647
wmd_friend_money: 1.3623729929992443
wmd_money: 1.3719341725658072
wmd_key_friend: 1.3510619566617341
wmd_money_friend: 1.3748713578849237
wmd_friend_friend: 1.3515046877307428
wmd_friend: 1.3589631477692967
wmd_key_key: 1.3683224375954064
wmd_money_key: 1.3873300243278976
wmd_friend_key: 1.389310619768149
wmd_key: 1.38154230411446
wmd_key_money: 1.3687879697563432
wmd_money_money: 1.3641149246383637
wmd_friend_money: 1.3670090618288386
wmd_money: 1.3665993433891102
wmd_key_friend: 1.3826764570745231
wmd_money_friend: 1.3476656775828681
wmd_friend_friend: 1.3464507796774345
wmd_friend: 1.359090216673696
wmd_key_key: 1.3679956890846563
wmd_money_key: 1.3824532398456242
wmd_friend_key: 1.379036192074747
wmd_key: 1.3765861616089
wmd_key_money: 1.3878793031688443
wmd_money_money: 1.3803586789773576
wmd_friend_money: 1.3818907898537864
wmd_money: 1.3833354010432914
wmd_key_friend: 1.3987385543761355
wmd_money_friend: 1.389920680897041
wmd_friend_friend: 1.3720191103124517
wmd_friend: 1.387370157077465
wmd_key_key: 1.3900545432778608
wmd_money_key: 1.3902868153914472
wmd_friend_key: 1.393588157911507
wmd_key: 1.3913239433050157
wmd_key_money: 1.3861147352604284
wmd_money_money: 1.3791788546708952
wmd_friend_money: 1.3927924827484004
wmd_money: 1.3860277241025967
wmd_key_friend: 1.3772383398108174
wmd_money_friend: 1.3832657096047896
wmd_friend_friend: 1.3754215780983332
wmd_friend: 1.3786576459056987
wmd_key_key: 1.393345491976762
wmd_money_key: 1.3700716799680872
wmd_friend_key: 1.3653756069089054
wmd_key: 1.3693250089721383
wmd_key_money: 1.3784790507915297
wmd_money_money: 1.3829421942202458
wmd_friend_money: 1.3914590356149767
wmd_money: 1.3866555171597312
wmd_key_friend: 1.3324090889216842
wmd_money_friend: 1.3912576377378136
wmd_friend_friend: 1.382452251225781
wmd_friend: 1.3834520785092903
wmd_key_key: 1.3900374059469538
wmd_money_key: 1.3985898252711264
wmd_friend_key: 1.3737611510605237
wmd_key: 1.3865695025544171
wmd_key_money: 1.3888853001735464
wmd_money_money: 1.3802805087813217
wmd_friend_money: 1.3906226525878451
wmd_money: 1.38672813321876
wmd_key_friend: 1.3768877506641644
wmd_money_friend: 1.3679216412527004
wmd_friend_friend: 1.3778863410825803
wmd_friend: 1.3743269138760734
wmd_key_key: 1.3837992178172067
wmd_money_key: 1.3618664453966574
wmd_friend_key: 1.3950742753004926
wmd_key: 1.3819495512668356
wmd_key_money: 1.3806155499454513
wmd_money_money: 1.3633863942884055
wmd_friend_money: 1.405428259965384
wmd_money: 1.3827525785685262
wmd_key_friend: 1.3755856454915865
wmd_money_friend: 1.334645451850048
wmd_friend_friend: 1.3229398297735788
wmd_friend: 1.3555522982267267
wmd_key_key: 1.3967765261714873
wmd_money_key: 1.4058563314540222
wmd_friend_key: 1.3841628125078749
wmd_key: 1.395598556711128
wmd_key_money: 1.3830880480476804
wmd_money_money: 1.3907655156506173
wmd_friend_money: 1.394479875468116

In [9]:
pilot_data[0:3]

,Prolific_ID,subject,key1,key2,key3,key4,key5,key6,key7,key8,...,wmd_friend_key,wmd_key,wmd_key_money,wmd_money_money,wmd_friend_money,wmd_money,wmd_key_friend,wmd_money_friend,wmd_friend_friend,wmd_friend
0,5d53bffa147a7d00015aae5a,1,Door,Gate,Outside,Grass,Itchy,Rash,Chicken pox,Shingles,...,1.391591,1.392383,1.384551,1.349149,1.383316,1.371180,1.385162,1.374462,1.345958,1.369324
1,5f00ec86304f7322eb8dfa41,2,Unlock,Door,Enter,Dreams,Time and space,Possibilites,Infinite,Time,...,1.364012,1.366217,1.372665,1.377063,1.383160,1.378248,1.364363,1.365838,1.377610,1.369997
2,5de27ced22383629b807cc70,3,Hole,Ground,Hog,Pig,Pork,Sald,Dressing,Clothes,...,1.369405,1.378907,1.375484,1.386651,1.355898,1.372919,1.357167,1.362013,1.394552,1.370782

In [11]:
# 단어 있는 버전 csv 저장
pilot_data.to_csv(processed_data_dir + 'distance_with_words.csv', index=None)

# 단어 컬럼들 드롭
drop_columns = pilot_data.columns[1:91]
pilot_data = pilot_data.drop(drop_columns, axis='columns')

# 단어 없이 coherence만 있는 버전 csv 저장
pilot_data.to_csv(processed_data_dir + 'distance.csv', index=None)